// @ts-check
/**
 * Local development bootstrap — makes the repo runnable on a fresh clone.
 *
 * 1. Ensures the local Supabase stack is running (starts it if not).
 * 2. Reads the local API URL / keys from `supabase status`.
 * 3. Writes apps/mobile/.env and apps/admin/.env.local (both gitignored).
 *
 * Local dev keys only — safe to keep on your machine, never commit them.
 * Cloud values (Vercel / EAS) are configured separately per environment.
 *
 * Usage: pnpm bootstrap   (from the repo root, after `pnpm install`)
 */
import { spawnSync } from 'node:child_process';
import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

/** Runs a command, inheriting stdio so long-running output streams live. */
function run(command, args) {
  return spawnSync(command, args, { stdio: 'inherit', shell: true }).status === 0;
}

/** Returns stdout of a command, or null on failure. */
function capture(command, args) {
  const result = spawnSync(command, args, { shell: true, encoding: 'utf8' });
  return result.status === 0 ? result.stdout : null;
}

function fail(message) {
  console.error(`\nsetup: ${message}`);
  process.exit(1);
}

// ── 1. Supabase stack ────────────────────────────────────────────────────────

console.log('setup: checking local Supabase status...');
let statusJson = capture('supabase', ['status', '-o', 'json']);

if (!statusJson) {
  console.log('setup: stack not running — starting it (first run pulls images, ~5-10 min)...');
  if (!run('supabase', ['start'])) {
    fail('`supabase start` failed. Is Docker Desktop running? Start it and re-run `pnpm setup`.');
  }
  statusJson = capture('supabase', ['status', '-o', 'json']);
}

let status;
try {
  // CLI 2.x emits a single JSON object; tolerate a trailing JSON-lines array.
  const parsed = JSON.parse(statusJson);
  status = Array.isArray(parsed) ? parsed[0] : parsed;
} catch {
  fail('could not parse `supabase status -o json` output.');
}

const { API_URL, ANON_KEY, SERVICE_ROLE_KEY } = status ?? {};
if (!API_URL || !ANON_KEY || !SERVICE_ROLE_KEY) {
  fail('`supabase status` did not return API_URL / ANON_KEY / SERVICE_ROLE_KEY.');
}

// ── 2. Env files ─────────────────────────────────────────────────────────────

const files = {
  [path.join(root, 'apps', 'mobile', '.env')]: `# Generated by pnpm setup — local Supabase dev values.
EXPO_PUBLIC_SUPABASE_URL=${API_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
EXPO_PUBLIC_SENTRY_DSN=
`,
  [path.join(root, 'apps', 'admin', '.env.local')]: `# Generated by pnpm setup — local Supabase dev values.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
# Server-only (bypasses RLS). Never expose to the browser or commit this file.
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
`,
};

for (const [file, contents] of Object.entries(files)) {
  if (existsSync(file)) {
    console.log(`setup: ${path.relative(root, file)} already exists — leaving it untouched.`);
    continue;
  }
  writeFileSync(file, contents, 'utf8');
  console.log(`setup: wrote ${path.relative(root, file)}`);
}

console.log(`
setup: done. Next:
  pnpm --filter admin dev      # Next.js admin  → http://localhost:3000
  pnpm --filter mobile start   # Expo dev server (press w for web, scan QR for device)

  Local logins (seeded): admin@kse.local / admin12345 · student1@kse.local / student12345
`);
