-- Supplemental seed for Jashore district: education institutions that
-- are present in the new authoritative list
-- (docs/List of Institutes in Jashore 2.md) but absent from the earlier
-- 20260926000001 Jashore seed.
--
-- Why this migration is needed
-- ----------------------------
-- The 20260926000001 seed was derived from a Wikipedia-style list that
-- captured only the district's **colleges** (institutions with
-- "College" / "Mahavidyalaya" / "Mahabiddalaya" in the name). The new
-- EIIN-based list (Jashore 2.md) covers ALL institution types: HIGH
-- SCHOOLS, SECONDARY SCHOOLS, MADRASAHS, POLYTECHNICS, TECHNICAL
-- TRAINING CENTERS, etc. — a few hundred entries that the original
-- college-only seed never recorded.
--
-- What this migration does
-- ------------------------
-- Walks every row of Jashore 2.md (1 row per EIIN, ~1014 total) and
-- emits an insert for each institution that is **not** already in the
-- database via the 20260926000001 seed. Name-matching is normalized
-- (case-insensitive, common spelling variants like Jessore/Jashore,
-- Mohila/Women's, Govt./Government, COLLAGE/COLLEGE, etc.).
--
-- Per-row classification rules (same as the other Khulna-division
-- supplemental seeds):
--   * type
--       - "COLLEGE" / "MAHAVIDYALAYA" / "MAHABIDDALAYA" / "DEGREE" /
--         "MOHILA COLLEGE" / "ADARSHA COLLEGE" / "IDEAL COLLEGE" /
--         "COLLEGIATE" → 'college'
--       - "POLYTECHNIC" / "POLYTECNIC" → 'polytechnic'
--       - "MEDICAL COLLEGE" / "NURSING" (degree/diploma, not a
--         nursing _training_ centre) → 'medical_college'
--       - "ARTS COLLEGE" / "FINE ART" → 'arts_college'
--       - "MADRASA"/"MADRASHA"/"MADRASAH" (Dakhil/Alim/Fazil/Kamil) →
--         'madrasa'
--       - "ENGLISH" / "PRE-CADET" (when clearly an English-medium
--         school) → 'english_medium' (rare in Jashore)
--       - "ENGINEERING INSTITUTE" / "TECHNICAL TRAINING" /
--         "COMPUTER TRAINING" / "VOCATIONAL" → 'technical_school'
--       - Everything else (HIGH SCHOOL, SECONDARY SCHOOL, PRIMARY
--         SCHOOL, GIRLS HIGH SCHOOL, JUNIOR HIGH SCHOOL, MODEL HIGH
--         SCHOOL, ACADEMY, INSTITUTION, BIDYAPITH, BIDDALAYA, etc.) →
--         'school'
--   * ownership_type
--       - 'public'  — name contains "GOVT" / "GOVERNMENT"; OR is a
--         known state-run institutional entity (Cantonment, BAF
--         Shaheen, Border Guard Public, Police Line, Collectorate,
--         P.T.I., Cadet College, Govt. Teachers' Training College,
--         Govt. Model Pilot School, NCTB/Board-affiliated, etc.).
--       - 'private' — otherwise.
--   * city     — 'Jashore' (the picker filters by this column when the
--                student picks Jashore as their district).
--   * area     — upazila name, matching the existing 20260926000001
--                seed's spelling (so the picker renders "<area>,
--                Jashore" consistently):
--                  "BAGHER PARA" → 'Bagherpara'
--                  "KOTWALI"     → 'Jashore Sadar'
--                  "MANIRAMPUR"  → 'Monirampur'  (matches existing
--                                                  Monirampur rows)
--
-- Re-running is safe: the partial unique index
--   (lower(name), coalesce(city, ''), type) WHERE is_active = true
-- silently skips identical active rows that already exist.

-- ── Abhaynagar Upazila (supplement) ──────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('58no. Siddhipasha Zealtala Govt. Primary School', 'school', 'public', 'Jashore', 'Abhaynagar'),
  ('Ab. Hamid T.M Secondary Girls School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Abhaynagar Pilot High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Ahamed Ali Sardar Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Airnet Computer and Training Center', 'technical_school', 'private', 'Jashore', 'Abhaynagar'),
  ('Akij Engineering Institute', 'technical_school', 'private', 'Jashore', 'Abhaynagar'),
  ('Al Helal Islame Academy', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Andha High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Ar Para High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Arpara Sayadia Balika Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Bagdha Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Baghutia High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Bahirghat Meseria Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Barni Bichali High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Basuari Senior Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Basuary Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Bhatpara Girls High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Bongram Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Chalishia High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Chapatala Chengutia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Computer Little Jewels School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('D.I.N.G.S. Unnayan Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dahlir Gati Hafizia Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Dahor Moshiahati Uttar Para Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dattagati Damukhali High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dattagati Girls High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Deapar Model Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dhopadi Adarsha High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dhopadi Daptaripara Shahidullah Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Dhopadi High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dhulgram Model High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Dumurtala Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Ektarpur Model High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Fakirhat High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Fulergati Horishpur Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Gazipur Roufia Kamil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Hidia A N H Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Hidia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('J. J. I. Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Joyarabad Sammilani High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Kodla High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Kota Fazil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Magura M. L High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Magura Siddikiya Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Mahakal B.C.C Muzakkedia Mohila Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Maricha Babanipur-Chakoi Dhakil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Mathurapur Purakhali Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Mohakal Girls Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Moshiahati ML High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Mothurapur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Mou Computer Training Center', 'technical_school', 'private', 'Jashore', 'Abhaynagar'),
  ('Nawly Gopinathpur Miloni Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Noapara Asia Computer Training Center', 'technical_school', 'private', 'Jashore', 'Abhaynagar'),
  ('Noapara Pilot Girls School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Noapara Shankarpasa High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Noapara High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Noapara Model Politecnic Institute', 'polytechnic', 'private', 'Jashore', 'Abhaynagar'),
  ('Noapara Model Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Nowapara Hizbullah Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Paira Islamia Fazil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Pathalia Siddiquia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Payrahat High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Potpara Paikpara Bhugilhat High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Purbachal High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Rajaghat Jafarpur Secondary School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Rajghaat Jafarpur Secondary Girls School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Raz Textile High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('S R Shuvarara Ranagati High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Sankar Pasa Kaderia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Saradanga Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Shankerpasha High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Sherajkati Durgapur Junior High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Shiddhip Asha Institution', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Siddhipasha P. B High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Siddipasha Ahamadia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Singari Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Singari Model High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Sorkhola High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Sundali Girls High School', 'school', 'private', 'Jashore', 'Abhaynagar'),
  ('Ziadanga Ahmadia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Abhaynagar'),
  ('Afsar Meherun Modern Collegiate School', 'school', 'private', 'Jashore', 'Abhaynagar');

-- ── Bagherpara Upazila (supplement) ──────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Azampur Islamia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Agra High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Andul Baria High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Andul Baria Ibna Abbas (R.) Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Azmeherpur K.A.Girls Dalhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('B.M. High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Bagharpara Pilot Girl''s High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Bagher Para Girls Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Bagher Para Siddiquia Fazil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Bagherpara Pilot Model Govt. High School', 'school', 'public', 'Jashore', 'Bagherpara'),
  ('Bakri Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Bakri Multilateral Secondary High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Bandabila B.C Roy Secondary School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Barvag Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Basati Computer Training Institute', 'technical_school', 'private', 'Jashore', 'Bagherpara'),
  ('Birprotic Ishaq Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Boalia Basuria Junior High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Borvagh High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('C. S. A. Junior School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Chandipur Balika Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Chandipur High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Charavita High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Chatiantala Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Chatiantala Madhamic School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Choto Khudra A. H. S. Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Dargah Pur Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Dargahpur Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Dash Pakhia Siddiquia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Dayarampur Siddikia Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Dhalgram High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Dhupkhali Islamia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('G C T Kuytibarri Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Gaidhaghat High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Hazi Bagu Biswas Samsur Biswas Junior Secondary School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Indra High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Inka Computer Training Institute', 'technical_school', 'private', 'Jashore', 'Bagherpara'),
  ('Jahurpur Ram Gopal ML. High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Jamdia Hafizia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Jamdia High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Joynagar Muiussunnah Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('K.K.R. High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Karim Pur Hafizia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Karimpur High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Khajura Islamia Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Khalsh Nasrul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Khalshi Adarsha Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Khanpur High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Khanpur Siddiqia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Khatra Pala Girl''s Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Khazura Makhon Bala Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Krishna Nagor Secondary School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Madrashatul Banat Al Islamia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Mahmudpur Akber Ali Balika Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Mahmudpur C. S. C. Junior Girls School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Mahmudpur High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Mahmudrur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('N B K Sammilita ML High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Narikel Baria ML High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Narikel Baria Seba Sangha Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('P H L High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('P.H.L Karatia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Pachim Balrampur Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Paikpara High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Pathan Paekpara Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Purbo Paikpara Model Govt. Primary School', 'school', 'public', 'Jashore', 'Bagherpara'),
  ('Radha Nagar Aminia Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('S.B.R. Saitkhaly Girls High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Sammilani High School Betal Para', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Sammilita Vidyapith Bagdanga M.L. High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Sekenderpur Secondary School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Silumpur High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Sukdebpur Secondary School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('T.C.B. Golgolia Ideal Junior School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('The United Model School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Uttar Chadpur Hamidia Senior Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Vanguria High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Vitaballa Islamia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Vittaballah High School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Wadipur Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Bagherpara'),
  ('Rostompur Debinagor Kaikhali Ayapur Junior Secondary School', 'school', 'private', 'Jashore', 'Bagherpara'),
  ('Sholua Norsinghpur Junior Secondary School', 'school', 'private', 'Jashore', 'Bagherpara');

-- ── Chaugachha Upazila (supplement) ──────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('A.B.C.D. High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Ander Kota Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Anderkota High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Andulia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Andulia High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('B K H Seconary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('B P R N Junior Girls High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Bade Khan Pur Siddiqia Dakil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Bariali Howly Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Borni Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Borni Ramkrishnapur Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Chandpara High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Chandrapara Govt. Primary School', 'school', 'public', 'Jashore', 'Chaugachha'),
  ('Chowgacha Hazi Sardar Matraz Ali High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Chowgacha Kamil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Chowgacha Medical Institute and Technology', 'technical_school', 'private', 'Jashore', 'Chaugachha'),
  ('Chowgacha Model High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Chowgacha Shadat Govt. Model Pilot Secondary School', 'school', 'public', 'Jashore', 'Chaugachha'),
  ('Chowgachha Upazilla Parishad Lyceum School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Chowgaha Sara Pilot Girls High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('D.M.C.U Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Dargahpur Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Dashpakhía Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Digre Dhakil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Garibpur Asarsha Bidyapith', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Guatoli Makanussunnat Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Hakimpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Hakimpur Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Hazrakhana Pir Blue Dwan Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Hizli Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('I. P. Powro Junior Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('J. H. D. Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('J. T. K. U Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Jagodishpur Mirzapur Ismail Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Jhawtala M.K.N.G Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Jhenaykundo Sadipur Jamia Jr Girls School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Kamlapur High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Kandi Adersha High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Katgora Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Khalsy Bazar Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Kharincha Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Kharincha Junior Girl''s School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('M.T.V Secondary (Prorosed) Girl''s School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Makapur Ballovepur Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Makapur Dakil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Mashila Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Mukterpur Am Zamtala High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Muktinagar Shaheed Smarani High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Narayanpur B.U. Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Patibila Hazi Shahajahan Ali High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Patibila Niamotpur Tahzibul Umma Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Purahuda Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('R.C.M T.U. High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('R.P.U. Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Raghunathpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Rajapur Adarso High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Rani Ali High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('S,K, Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Sahapur Nagar Barni High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Salua Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Sammilani High School, Dhuliani', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Sanchandanga and Kakuria (S&K) High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Sarpraj Pur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Sayedpur Siddquia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Shahazadpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Shinghajhully Senior (Alim) Madrasa', 'madrasa', 'private', 'Jashore', 'Chaugachha'),
  ('Shinghajhuly Moshiur Rahman Memorial High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Shishutala Ashim Kumar High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Sukhpukuria High School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Swarupdaha Secondary School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Uzirpur M.P.J.B Secondary Girls School', 'school', 'private', 'Jashore', 'Chaugachha'),
  ('Chowgacha Marks Institute and Technology', 'technical_school', 'private', 'Jashore', 'Chaugachha');

-- ── Jhikargachha Upazila (supplement) ────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Atalia Alimul Quran Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Al Hazz Rofi Uddin Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Alauddin Biswas Model Academy, Gulbagpur', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Alimonnessa Girls High School and Technical College', 'college', 'private', 'Jashore', 'Jhikargachha'),
  ('Amini Ramchandrapur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Amrito Bazar Girls School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Angar Para Bohi Ram Pur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Ashingri ND Model Secondary Girls School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Baisa Chandpur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Baisha Chadnpur Dakhil Madrsha', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Bakura J-Kati Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Baliagourshuti Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Baliadanga U P Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Balla B.N.K. High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Balla Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Bankra J.K High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Bankra Mukundprur Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Barnamala Bidyapith Kamarpara', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Bausha R.N. Secndary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Bejiatala Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Bish Hori Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Bodkhana High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Bodkhana Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Boro Podaulia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Chutipur Secondary Girls School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Dahar Magura Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Dhan Pota High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Digdana Khoshalnagar Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Digdana Khoshalnagar High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Digdana S.I. Girls Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Ehsan Computer Training Center', 'technical_school', 'private', 'Jashore', 'Jhikargachha'),
  ('F. J. U. B. High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Ganganandapur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Gazir Dargah Foizabad Fazil B.A Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Horidrapota Abdul Gofur Adarsa High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('J D P K Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Jharna Training Center', 'technical_school', 'private', 'Jashore', 'Jhikargachha'),
  ('Jhikargach Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Jhikargacha B.M. High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Jhikargacha Darul Ulum Kamil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Jhikargacha H. S Junior High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Jhikargacha M.L Model Govt. High School', 'school', 'public', 'Jashore', 'Jhikargachha'),
  ('Jhikargacha Pilot Girls High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Jhikargachha Sammilani Girls High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Kagmari Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Karimali R.A.K. Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Kashipur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Kawria B.C Junior School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Kayem Kola High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Kayemkola Nesaria Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Kharusha Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Kholshi Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Kulbari B K S High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Kulia Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Laujani N.M. High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('M.C.D Sammilani High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('M.K. Adarsha Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Magura Dahar Magur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Matasia High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Matikumra High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Matshia Darus Sunnah Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Misrideara Bahirampur Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Mokam Tala Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Mokamtala Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('N.U.R.S. United Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Nabib Nagar Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Nabrun Secondary Girls School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Nischintapur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Parbazar Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Raghunath Nagar Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Razapur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Saint Louis High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Sammilita High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Shimulia S.M.P.K. High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Shiordah High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Sonakur Zakaria Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Soto Podaulia P.U.R Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Sreerampur High School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Sreerampur Siddeqia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha'),
  ('Suratjan Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Swopner Shiri Computer Academy', 'technical_school', 'private', 'Jashore', 'Jhikargachha'),
  ('Taora Azizur Rahman Secondary School', 'school', 'private', 'Jashore', 'Jhikargachha'),
  ('Ujjalpur Shahid Muktizodda Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jhikargachha');

-- ── Keshabpur Upazila (supplement) ───────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('A.B.G K. Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Adarsha Secondary Girl''s School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Altapole High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Arua High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Arua Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Atanda S. L. High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Aulgati Ideal High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Baga R N Ideal High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Baga Shah Kararia Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Baisa Sreerampur Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Baisha Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Bakultala Bazar Mahla Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Baliadanga Sarbajonin Debaloy High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Baliadanga Surbanjin Debalay Technical High School', 'technical_school', 'private', 'Jashore', 'Keshabpur'),
  ('Banshbaria Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Barenga Sammilani Bidhyapith', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Baruihati Pattro Para S.B.Gitls Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Bashbaria High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Baushala Girls High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Bausola Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Begumpur High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Begumpur Islamia Balika Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Betikhola Darussunnah Dakil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Bhadrapolly Junior Girl''s School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Bhalukaghar Girls Junior School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Bhalukghar Azizia Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Bhalukghar Multilateral High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Bhandar Khola Dalhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Bhander Khola Sammilani High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Bharat Bhaina Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Bidyandanakati Rash Behari Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Boranga N. S. H Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Burihati ML High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Burihati Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Buruli School and College', 'college', 'private', 'Jashore', 'Keshabpur'),
  ('Chandra Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Chingra Dharmopur Darus Sunnah Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Chingra Ideal High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Chuadanga Krishna Nagar High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Dauly Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Dormutia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Dormutia Sammiloni Secondary Girls School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Dourmotia High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Fatepur Rahim Miya Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Garbhanga High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Garbhanga Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Garbhanga Secondary Girls School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Gholghata Darussunnah Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Gourighona Sommilone High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Hasanpur Darus Sunna Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Hizal Danga Ideal Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Imannagar M, B, G, Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Kakilakhali Sammilani Girls High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Kaliary S.B.L. Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Kanaidanga High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Kariakhali Jr. Girl''s School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Kasta Gahar Ali Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Katakhali High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Keshabpur B. U. Kamil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Keshabpur Darul Ulum Mahila Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Keshabpur Madhu Shiksha Niketon High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Keshabpur Pilot Girls High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Khatiakhali Junior Girls School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Komarpol Islamia Sabania Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Komorpole Girls High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Laxminath Kathi Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('M. M Gobindapur High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Madhykul Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Maguradanga Islamia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Mahadeb Pur R B S High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Mangalkote ML. High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Meherpur Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Mirzapur Women Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Mominpur R, K, M Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Monohornagar Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Muktizoddha Technical High School', 'technical_school', 'private', 'Jashore', 'Keshabpur'),
  ('Mulgram Darul Ullum Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Mulgram Junior Girls School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Mulgram Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Narayanpur Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Natun Mulgram Darul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Nehalpur Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Nutan Mulagram High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('P. B. H High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Palli Unnayan Girls High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Pancharohi T.S Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Panjia Adarsha Girls High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Panjia M.N. Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Panjia Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Pathra Pally Unnayan High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Pathra Sidikia Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Proatappur Nivarani High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Protap Pur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Ragnagor B.M. High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Ramchandra PuR Panchpur Darga Mohila D. Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Ramchandrapur Islamia Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Razakati Shaheed Pre Ziaur Rahman High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Roghuram Pur Women Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('S,S,G,Teghori D,U Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('S.M High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('S.S.G. Barandaly Darul Ulum Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Sagardari Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Sagardari Michael Madhusudan Institution', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Sagardari Sonet Junior Secondary Girl''s School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Sannyagacha Balika Dkakil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Sarutia Balika Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Sataishkati B. D High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Satbaria Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Satbaria Secondary Girl''s School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Satbaria Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Shahapur Meherunnessa Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Shikarpur M.L. High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Sreefal Kalia Roy Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Sreepur Adarsha Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('SSG Barandali Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Sufalakati Secondary School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Teghori Palli Mongal High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Tita Bazit Pur M K B Girls School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Trimohine Girl''s High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Trimohine High School', 'school', 'private', 'Jashore', 'Keshabpur'),
  ('Trimohini Darul Islam Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Keshabpur'),
  ('Verchi Secondary School', 'school', 'private', 'Jashore', 'Keshabpur');

-- ── Jashore Sadar (Kotwali) (supplement) ─────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('A D P Sammilani Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Abdul Bari ML. Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Abdul Gafur Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Abdul Gafur Memorial Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Abdus Samad Memorial Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Ad-Din Nursing Institute', 'technical_school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Adabia Darul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Alam Nagar Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Ambattala Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Amdabad Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Ameenah Ahmed G. T. Model Secondary Girls School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Anjuman Ara Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Aysha Adarsha High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('B. R. B Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('B.M.S. Junior Secondary School Mobarokkati', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('B.M.S. Junior School Baladanga', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Badshah Faisal Islami Institute New Town', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Badshah Faisal Islami Institute Eidgah', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Bagdanga Junior High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Bahadurpur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Baje Durgapur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Baje Durgapur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Balarampur Adarsha Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Balia Vekutia A High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Baniargati Mohila Model Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Barnamala Bidyapith Jessore', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Barnamala Edas School, Jessore', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Basundia Model Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('BCMC College of Engineering and Technology', 'polytechnic', 'private', 'Jashore', 'Jashore Sadar'),
  ('Bhatpara Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Biman Bandar Bidyaloya, Jessore', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Bir Muktijoddha Fashiar Rahman Junior High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Birsreshtha Nur Mohammad National Cadet School', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Bonogram Gaid Gachhi Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Border Guard Public School Jessore', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Chandutia, Arispur, Gobindapur, Motbari High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Cantonment Board Secondary School', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Cantonment High School', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Chanchra High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Chandpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Chandutia M. I. Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Chatian Tala K I Senior Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Chhatian Tala Churmonkati High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Daitala Adarsha Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Dakatia High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Danbir Haji Md Mohasin High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Darus Sunnat Mozaddadia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Daulatdihi M.M. Mohila Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Deapara High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Dogachhia Ahsan Nagar Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Fulbari Model School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Fulbari Siddin Awolia Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Fultala Abedia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Ghrulia Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Ghuni High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Gopalpur D.S. Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Govt. Teachers'' Training College, Jessore', 'college', 'public', 'Jashore', 'Jashore Sadar'),
  ('Hamidpur Darul Aman Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Hamidpur ML High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Hashimpur ML. High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Hazrat Shah Waliullah Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Hogladanga Sha Bakher Ullah Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Ichhali Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Islamia Girls High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jagannathpur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jagonnatepur Shibanondapur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Janal Badhal High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jashore University of Science and Technology (JUST) School and College', 'college', 'public', 'Jashore', 'Jashore Sadar'),
  ('Jayenta High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jess Residential Pre-Cadet School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jessore Aminia Kamil Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jessore Adarsha Bilika Biddalaya', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jessore Collectorate School', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Jessore Govt. Girl''s High School', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Jessore Mohila Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jessore Night High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Jessore Polytechnic Institute', 'polytechnic', 'public', 'Jashore', 'Jashore Sadar'),
  ('Jessore Teachers Training College', 'college', 'public', 'Jashore', 'Jashore Sadar'),
  ('Jessore Zila School', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('K J H Islamy Academy High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kachua High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kallayanda Goaldah Bazer Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kashimpur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kazi Shamsul Huda High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kazipur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Khajura M. N. Mitra Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kharichadanga High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Khojar Hat Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kholadanga Adarsha Junior Secondary Girls School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Kuada Darussunna Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Lebutala High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mahamudur Rahman ML. High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mahidia High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mahidia Sommeloni Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Malonchi Junior High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Meghla High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mirapur Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Model Polytechnic Institute', 'polytechnic', 'public', 'Jashore', 'Jashore Sadar'),
  ('Momin Nagar Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Monaharpur Darul Hadis Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Monshop Shaikh Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Moriyam Bibi Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mothurapur Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mukteshwari High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Municipal Preparatory High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Munsef Pur Ideal High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Munshi Meher Ullah Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Munshi Meherulla Teachers Training College', 'college', 'private', 'Jashore', 'Jashore Sadar'),
  ('Muslim Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Namej Sarder Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Narangali Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Narangali Sammilita Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Narendrapur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Newtown Secondary Girls School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Nursing Institute, Jessore', 'medical_college', 'public', 'Jashore', 'Jashore Sadar'),
  ('Nutan Khayertala Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Osmanpur Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('P.T.I. Jessore', 'college', 'public', 'Jashore', 'Jashore Sadar'),
  ('Padmabila Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Panch Baria Girl''s High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Police Line Secondary School, Jessore', 'school', 'public', 'Jashore', 'Jashore Sadar'),
  ('Progoti Maddhamik Balika Bidalay', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Pulerhat Girls High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Pulerhat High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Puratan Kashba Darul Ulum Khaimul Islam Fazil Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Purbo Bashundia Girl''s High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rajapur Jamia Deenia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rohelapur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rudrapur B.L. High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rupdia Balika Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rupdia Adarsha Jr. School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rupdia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rupdia Sahid Smritee Girl''s High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Rupdia Welfare Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sacred Heart High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sakhina Girls High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sammilani Institution', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sankerpur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sarapole Darus Salam Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sarapole High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Satighata High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sekhhati Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Seva Sangha Girls High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Shahbaz Pur High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Shankhari Gati ML High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Shankhari Gati Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sheela Ray Chowodhury High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Shekhati Shafiar Rahman Model Academy', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Singia Hafigia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Siraj Singa Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sripodi Ghoragachha Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sultanpur Nurul Islam Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Sura Secondary School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Talbaria ML High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Talbaria Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Technical Training Center, Jessore', 'technical_school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Textile Vocational Institute, Jessore', 'technical_school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Tirerhat Shaihd Idris Memo High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Tirerhat Siddekia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Tokyo Bangla Polytechnic Institute', 'polytechnic', 'private', 'Jashore', 'Jashore Sadar'),
  ('Topsi Danga Islamia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Upashahar Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Upashahar High School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Upashahar Teachers Training College, Jessore', 'college', 'private', 'Jashore', 'Jashore Sadar'),
  ('Vagabatipur Shotighata Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Zirat Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Jashore Sadar'),
  ('Naba Kishalay School, Jashore', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Daitala Junior Secondary Girls School', 'school', 'private', 'Jashore', 'Jashore Sadar'),
  ('Mukto Bangla Science and Agriculture Technical Institute', 'technical_school', 'private', 'Jashore', 'Jashore Sadar');

-- ── Monirampur Upazila (supplement) ──────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Chandua Somoskati Junior Girl''s School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bagdob Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Balidha Panchakari Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Bashudebpur Siddiqua Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Khanpur Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Parkhajura Siddiqua Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Shah Ali Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('A. G. M Junior High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Ahmed Ali High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Al Haz Hanief Ali Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('B.B.G.H.S Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('B.D. High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('B.H.M.S. Junior Girls School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bagdanga Dahakula Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bahadur Pur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bahir Ghoria Gopal Pur Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Bajitpur Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bakoshpol Adarsa High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Balia Danga Dkahil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Baliadanga Khan Pur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Balidah Panchakari High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Balidha Model Junior Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bangalipur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bharatpur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bhawanipur Ramuttam High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Bijoyram Pur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Biprokona Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Boalia Ghat High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Boro Chatla Kola High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('C. T. K Adarsha Junior Girl''s School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Chakla Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Chakla Mohila Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Chandpur Majhiali High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Chapatala High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('China Tola Technical High School', 'technical_school', 'private', 'Jashore', 'Monirampur'),
  ('Chinatola Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Danga M.P. Adarsha High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Danga Mohisdia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Deluabari Highn School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Dhakuria Islamia Dhakil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Dhakuria Protapkati M.L. High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Dhaligati Sundal Pur Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Dholigati High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Dighir Par Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Digonga Kuchlia Haridaskati High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Dumur Khali Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Dumurkhali Sammilani High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Durbadanga Batbila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Durgapur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Enayet Pur B.G.H Girl''s High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('G.H. Pardia High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Gabukhali High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Galda Kharinch High Girls School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Galda Kharinchi Sammiloni High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Galdakharinchi D.H.S. Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Gangulia Adarsha Girl''s High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Gobindopur Teghori Adorsho Mohila Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Gopikanta Pur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Goribpur Chandpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('H.R.H. Shammilani Junior High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Hakimpur Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Halsha Adarsho Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Harina High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Hatgachha High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Hayatpur Dakhil Nadrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Hazrakathi Darul Ulum Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Hazrakati Ahamedia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Hazrakati Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Helanchi Krishabati Balika Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Helanchi Krishnabati High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Helanchi Krisnabati Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Hogladabga Darussubbah Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Hogladanga Kagirgram Koramara High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Itta Model High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Itta Sluis Ghat Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Jalal Pur Junior High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Jaljhar Siddiqia Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Jaljhara Khaddrogangra Junior High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Jhanpa Balika Dhakil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Jhanpa Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Jhanpa Secondary Ideal Girl''s School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Jhanpa Uttar Para Junior High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Joka Dighirpar Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Joypur Adarsha Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Joypur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('K.H.N. High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kadam Baria Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Kalar Hat Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Kalarhat High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kamalpur Siddiquia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Kaminidanga Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kantaltala Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kapalia High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kashim Nagar High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kashipur Siddiquia Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Kasimpur Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Khajura Kathal Tala High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Khalia M.H. Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Khamar Bari High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Khankya Hasania Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Khatuadanga High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Khatura Modhupur Cayemcola High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Khedapara Gangulia Fajil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Khedapara Pallimongol High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kismoth Chakla Gl. Jr High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kodalpara Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Komolpur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kuada Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kultia Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Kumar Ghata Dhkhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Kushkhali Assannagar High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Lakhai Danga Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Lakmikatopur Moswimnagar Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Laukunda Alahia Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Lauri High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Lauri Ramnagor Kamil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Laxmanpur R. Adarsha Mohila Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Madanpur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Manirampur Govt. Pilot High School', 'school', 'public', 'Jashore', 'Monirampur'),
  ('Manirampur Model Polytechnic Institute', 'polytechnic', 'private', 'Jashore', 'Monirampur'),
  ('Modhupur Bahadurpur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Modinatul Ulum Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Modonpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Mohadebpur Joynagar Darul Ulum Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Mohadebpur Adarsha Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Monirampur Adarsha Sammiloniee High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Monirampur Adarsha High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Monirampur Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Monirampur Govt. Girls High School', 'school', 'public', 'Jashore', 'Monirampur'),
  ('Monirampur Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Monirampur Tecnical Vocational Institut', 'technical_school', 'private', 'Jashore', 'Monirampur'),
  ('Monohar Pur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Monohar Pur Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Monoharpur Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Moshiahati Akhaya Diploma in Agriculture and Fisheries Technical Institute', 'technical_school', 'private', 'Jashore', 'Monirampur'),
  ('Moshwim Nagar Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Muktarpur Gowalbari Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Muragacha High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Nagor Ghope High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Nebogati Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Nehalpur Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Nengura Hat Darul Ulum Senior Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Nengurahat Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Noyali Khatal Tala D. Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Padma Nath Pur Junior Girl''s School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Palasi Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Panchbaria Panchkatia High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Panchkatia High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Panchkatia Panchbaria Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Pardia Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Pariali Adarsha Balika Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Parkhajura Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Patan Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Paton Juranpur Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Poradanga R. C. Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Pourasava Girl''s High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Rais Uddin Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Rajganj Siddquea Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Rajgonj High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Rajgonj Mobarakpur Mohila Alim Madrsha', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Rajgonj Shaheed Smrity Maddumic Balika Viddapith', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Rajipur K.M.S High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Ramnagor High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Ratandia Islamia Balika Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Rohita Secondary School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Sahida Sultana High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Satgati Amrojhuta Jr. High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Shahid Swarani Jhanpa M L High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Shamkur Jomjomia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Shamser Bag Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Shaylahat High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Shoily High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Shyam Nagar M. High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Shyamkur M L High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Silumpur Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Solokhada High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Sreepur Adarsho Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Subal Kati Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Subalkati Girls High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Sundalpur Agar H.H.G Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Sundalpur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Tazpur High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Tengramari Sammiloni High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Thkerghat Secondary Girl''s School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Toniaghara Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Monirampur'),
  ('Tripurapur Junior High School', 'school', 'private', 'Jashore', 'Monirampur'),
  ('Prottasha Computer Training Centre', 'technical_school', 'private', 'Jashore', 'Monirampur'),
  ('Dr Momtazul Islam Technical School', 'technical_school', 'private', 'Jashore', 'Monirampur'),
  ('Jashore Govt Survey Institute', 'technical_school', 'public', 'Jashore', 'Monirampur');

-- ── Sharsha Upazila (supplement) ─────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Lautara Rabetaul Ulum Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Amil Mohammadia Mohila Dakhi Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('B.R.D. Shimata Junior Secondary High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Bag Anchara United Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Bagan Chara Balika Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Baganchara Siddiquia Senior Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Bahadurpur Mohila Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Bahadurpur Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Bahadurpur Sonamukhi Model High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Balunda Aminai Dakhil Madrsa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Balunda High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Bamunia Sonatoni Kati Girls High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Barnamala Bidyapith, Ulashi', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Baropota United Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Barpouta Siddiquia Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Basat Pur Hossainia Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Basatpur Colony Govt. Primary School', 'school', 'public', 'Jashore', 'Sharsha'),
  ('Benapole Madinatul Ulam Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Benapole Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Benapole Mohila Senior Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Bondhon Computer Training Institute', 'technical_school', 'private', 'Jashore', 'Sharsha'),
  ('Buruj Bagan Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Buruj Bagan Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Buruj Bagan Pilot Girls High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Chalitabaria R.D. High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('D.S.T. High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Dhannya Khola D S Fazil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Dhanyakhola High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Sharsha Govt. Women''s College', 'college', 'public', 'Jashore', 'Sharsha'),
  ('Gatipara Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Ghiba Darul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Goga Kaliani Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Goga Kaliani High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Gokarna Sharatala Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Gopalpur Ichapur Aminia Dhakil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Gorpara Secondary High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Habibur Rahman Biswas Secondary Public School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Kaiba Baikola Osmania Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Kaiba Baikola High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Kadaha Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Kandarpapur Darul Islam Mahila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Keralkhali Pariarghope Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Kudlarhat High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Lakshman Pur Darul Hadis Dakhil Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Mohishapir Abdus Sobhan Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Morium Memorial Balika Biddalaya', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Muktejoddha GKGS Girls High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Nabo Diganta Pre-Cadet and Junior School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Navaran Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Nischintapur Darus Salam Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Nizampur Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Pakshia Sammilani Girls High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Pakshia Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Panch Bhulat Dakkhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Putkhali Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Rahim Pur Alim Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Rari Pukur Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Samta Siddikia Fazil Madrasah', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Saratala Girls High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Sarsha Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Satai A.C.I United High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Sharatala Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Sharsha Girls High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Sharsha Model Pilot Govt. Secondary School', 'school', 'public', 'Jashore', 'Sharsha'),
  ('Shikri Madinatul Ulum Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Sikarpur Sammiloni High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Skynet Computer Training Institute', 'technical_school', 'private', 'Jashore', 'Sharsha'),
  ('Skytech Computer Training Institute', 'technical_school', 'private', 'Jashore', 'Sharsha'),
  ('Sonanodia Gati Para D.S Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Sunrise Public School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Tabibur Rahman Sardar Secondary High School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Tangra Mohila Alim Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha'),
  ('Ulashi Secondary School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('United Adarsha Girl''s School', 'school', 'private', 'Jashore', 'Sharsha'),
  ('Goyra Meherun Habib Dakhil Madrasa', 'madrasa', 'private', 'Jashore', 'Sharsha');







