-- Seed the Kushtia education institutions list (Kushtia district only).
-- Source: docs/List of Institutes in Kushtia.md (a single mixed table — every
-- row classified by name into one of the schema enums).
--
-- Mirrors the Khulna / Satkhira / Jashore / Bagerhat / Magura / Narail seeds:
--   * type           — 'university' for universities (incl. Islamic
--                      University, Kushtia; Robindra Maitree University;
--                      Lalon University of Science and Arts),
--                      'medical_college' for medical colleges (incl.
--                      homeopathic), 'polytechnic' for polytechnic
--                      institutes, 'college' for any degree / higher-
--                      secondary college (incl. mahavidyalaya, mohabiddyalay,
--                      technical school-and-college, agricultural college,
--                      nursing institute, business management college,
--                      teachers training college, English-version school-
--                      and-college), 'madrasa' for dakhil / alim / fazil /
--                      kamil / islamia madrasas, 'technical_school' for
--                      free-standing technical / engineering / vocational /
--                      physical / agricultural institutes, 'school'
--                      otherwise. Border Guard Public / Police Lines /
--                      Collectorate / Zilla / Govt. / Government rows are
--                      marked public; "Pilot" without "Govt" stays private.
--   * ownership_type — 'public' for "Govt." / "Government" institutions and
--                      for institutional entities run by the state
--                      (Collectorate, Police Lines, Border Guard Public,
--                      Islamic University, BGB, Zilla schools, PTIs).
--                      'private' otherwise.
--   * city           — always 'Kushtia' (the picker filters by this column
--                      when the student picks Kushtia as their district)
--   * area           — upazila name (no "Kushtia" suffix, since city already
--                      says Kushtia).
--
-- Source-quality notes (kept as-written for traceability):
--   * "<br>" tags inside names are stripped.
--   * Apostrophes inside names are doubled for SQL ("GIRL'S" → "GIRL''S").
--   * Multiple consecutive spaces collapsed to one.
--   * Typographic typos preserved (e.g. "COLLAGE", "SECONDRY", "MADRSAH",
--     "COLLGE", "BIDDALOI", "SHCOOL", "VIDDALAY", "MADEHAMIK", "SCOHOOL",
--     "TARGORE", "HOMIOPATHIC", "MADRSAHA"). Easy to normalise in a
--     follow-up if desired.
--
-- Re-running is safe: the partial unique index
--   (lower(name), coalesce(city, ''), type) WHERE is_active = true
-- dedupes identical active rows.
--
-- Upazila row counts:
--   * BHERAMARA     — 40
--   * DAULATPUR     — 119
--   * KHOKSA        — 37
--   * KUMARKHALI    — 89
--   * KUSHTIA SADAR — 115
--   * MIRPUR        — 82
--   * Total         — 482

-- ── BHERAMARA Upazila (40) ──────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('A.S.K.M.P. High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Abdul Hoque Girls High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Azad Memorial Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('B.J.M College', 'college', 'private', 'Kushtia', 'Bheramara'),
  ('Bahadur Pur Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Bheramara'),
  ('Bahadurpur Girls High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Bahadurpur Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Bahir Char Sholodag Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Bheramara'),
  ('Bheramara Adarsha Degree College', 'college', 'private', 'Kushtia', 'Bheramara'),
  ('Bheramara Alim Madrasa', 'madrasa', 'private', 'Kushtia', 'Bheramara'),
  ('Bheramara College', 'college', 'private', 'Kushtia', 'Bheramara'),
  ('Bheramara Govt. Mahila College', 'college', 'public', 'Kushtia', 'Bheramara'),
  ('Bheramara Pilot High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Chandipur Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('D.M Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Damukdia Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Dharampur Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Engineering and Technology Institute', 'technical_school', 'private', 'Kushtia', 'Bheramara'),
  ('Foyzullapur Secondry Girls School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Govt. Bheramara Pilot Secondary Girls High School', 'school', 'public', 'Kushtia', 'Bheramara'),
  ('Halima Begum Academy Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Hazi Afsar Uddin Secondary Girls School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Hazi Wazed Ali Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Hirimdia Govt. Primary School', 'school', 'public', 'Kushtia', 'Bheramara'),
  ('J.M Scondary Girls School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Jogswar Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Juniadha Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Kofejan Nesa and Hazi Niamot Ullah High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Mokarimpur Girls High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Pachim Bahir Char 12 Mile Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Bheramara'),
  ('Paran Khali High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Patua Kandi High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Power Developement Board Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Rahima Afsar Junior Secondary Girl''s School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Raita High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Sabujkali Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Satbaria Bhabanipur High School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Sholodag Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Taher Secondary School', 'school', 'private', 'Kushtia', 'Bheramara'),
  ('Bheramara Technical School and College', 'college', 'private', 'Kushtia', 'Bheramara');

-- ── DAULATPUR Upazila (119) ─────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Ahasan Nagar Technical and Business Management College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('B.D.S. High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('P.M. Ideal Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('A M H Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Adabaria High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Adabaria Union College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Adarsha High School Joyrampur', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Akida Junior Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Al Saleh Junior School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Allardarga Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Amdaha High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Aria United High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Ashish High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('B T P High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('B. M. Junior Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('B.C.K Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Bagoan K. C. V N High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Bahirmadi High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Bairagir Char Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Baitun Noor Alim Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Balir Diar Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Baragangdia Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Baragangdia Siddiquia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Bargangdia Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Bazumara Islamia Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Bhurka Para J/R School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Bilgatua High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Boalia High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Boalia Secondary Girls'' School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Boiragir Char Rahimpur Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Chak Daulatpur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Chilmari Abdul Jabbar Hazi Pandab Ali High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('D.G.M. High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('D.G.T High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('D.G.T Junior Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Dari Para Model High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Daulat Khali High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Daulat Pur Pilot Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Daulatpur Girls College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Daulatpur College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Daulatpur Pilot Govt. Model High School', 'school', 'public', 'Kushtia', 'Daulatpur'),
  ('Dautlatpur Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Dharmadah High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Dighol Kandi Junior High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Dr. Ekramul Haque Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Dr. Mohammad Fazlul Haque Girls College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Faisal Wajed Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Fatema Yusuf Junior Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('G. N. Junior High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('G.T.C.P. High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Gachher Diar High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Goal Gram Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Goal Gram Natnapara Secondery Girls School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Goalgram College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Hasanpur Junior Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Hosenabad Technical School and College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Hossainabad Adarsha Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Insaf Nagar High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Islampur Secoundary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('J.M.G High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Jhaudia High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Jotashahi Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Kallyanpur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Kamalpur Secondary School, Daulatpur', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Kamalpur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Khalisha Kundi Secondary Girls School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Khalisha Kundi Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Khalishakundi Degree College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Kharijathak Secondari School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Khas Mathura Pur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Kishori Nagar Adarsha Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Koldiar Model High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Lal Nagar Adarsha High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Lal Nagar Krishi Institute', 'technical_school', 'private', 'Kushtia', 'Daulatpur'),
  ('M.G. Secondary Girls School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Madapur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Maricha Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Mirzapur Vurka Al Hera Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Mohis Kundi High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Mohiskundi College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Moin Uddin Biswas High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Motijheel G M S Junior High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Mozammel Hoque Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Muslim Nagar Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Nabogram Secoundary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Nasir Uddin Biswas College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Nasir Uddin Biswas Girls School and College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Nasir Uddin Biswas Non Govt Polytechnic Institute', 'polytechnic', 'private', 'Kushtia', 'Daulatpur'),
  ('Nuruzzaman Biswas College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('P. K. C. Junior High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('P.S.S. Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Pakuria Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Peoples Degree College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Philipnagar Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Philipnagar Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Phlipnagar Maricha College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Pipulbara Ahosana Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Pipulbaria High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Pragpur College', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Pragpur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Prantik High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Rabiul Awal Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Rahima Begum Academy', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Ram Krishina Jonion High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Rezwanul Ulum Alim Madrasah', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Rifaitpur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('S.M.N. High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Satar Para Secondary School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Shahid Eakub Ali Jr. Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Shahid Smiritty Junior Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Shehala Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Sheikh Fozilatunnesa Mujib Govt. Mohila College', 'college', 'public', 'Kushtia', 'Daulatpur'),
  ('Shoshidhar Pur Darun Nur Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Daulatpur'),
  ('Shyampur High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Tara Gunia Girls High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('Taragunia High School', 'school', 'private', 'Kushtia', 'Daulatpur'),
  ('TESL English Version School', 'english_medium', 'private', 'Kushtia', 'Daulatpur'),
  ('United College Balirdiar', 'college', 'private', 'Kushtia', 'Daulatpur'),
  ('Tekala Nimnomadhomik Biddaloi', 'school', 'private', 'Kushtia', 'Daulatpur');

-- ── KHOKSA Upazila (37) ─────────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Al Haz Saidur Rahman Montu Women College', 'college', 'private', 'Kushtia', 'Khoksa'),
  ('Alhaj Md. Sodor Uddin Khan Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('Alhaj Sadaruddin Khan Girls High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Ambaria Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('Ambaria High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Amlabari Secondary School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Banagram Girls High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Biharia Govt. Primary School', 'school', 'public', 'Kushtia', 'Khoksa'),
  ('Bilzani Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('Bonagram High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Bosowa Junior High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Chandot M.B Madinatul Ul Alim Madrasah', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('Dhokra Kole High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Dhokrakole Degree College', 'college', 'private', 'Kushtia', 'Khoksa'),
  ('Eaqub Ahmed Secondary School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Fulbari Secondary School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Goneshpur Qasemul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('Gope Gram A.Z. Fazel Madrasa', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('H.D. Azizur Rahman High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Husnul Ulum Alim Madrasa', 'madrasa', 'private', 'Kushtia', 'Khoksa'),
  ('Iswardi Secondary High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Joynti Hajra High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Khoksa Govt. College', 'college', 'public', 'Kushtia', 'Khoksa'),
  ('Khoksa Janipur Govt. Pilot High School', 'school', 'public', 'Kushtia', 'Khoksa'),
  ('Khoksa Janipur Pilot Girls High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Kofil Uddin Molla Junior Girls High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Komorvogh Ramanath Pur Junior Girls High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Moragachha High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Osmanpur High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Paikpara Mirjapur High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Ramanath Pur School and College', 'college', 'private', 'Kushtia', 'Khoksa'),
  ('Sengram Secondary School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Shimulia Secondary School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Shomospur Abu Taleb Degree College', 'college', 'private', 'Kushtia', 'Khoksa'),
  ('Shomospur Girls High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Shomospur High School', 'school', 'private', 'Kushtia', 'Khoksa'),
  ('Zabal E Nur Mohila Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Khoksa');

-- ── KUMARKHALI Upazila (89) ─────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Sultanpur Mahatabia High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Adarsha Mohila College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Adorsha Dhakil Madrasah, Sondah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Akmal Hossain Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Alauddin Ahmaed Dgree College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Alauddin Ahmed Physical Institute', 'technical_school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Alauddin Ahmed Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Alauddin Ahmed Teachers Training College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Alauddin Nagar Girls High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Atiar Rahman Secondary Girls School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('B.K.M.N. Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Bagulat High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Bahar Krishi College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Bansh Gram Fazil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Basgram Alauddin Ahmed Degree College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Batikamara Govt. Primary School', 'school', 'public', 'Kushtia', 'Kumarkhali'),
  ('Bharuapara Junior High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Bibi Asia Khatun Balika Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Birikoya Balika Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Buzruk Bakhai High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Cheuria High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Chourangi Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Chowrangi College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dakshin Monoharpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dansha Girl''s High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dansha High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dasha Mohor Ali Dakil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dayrampur Islamia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dhalnagar Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Durgapur Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Durgapur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Dwarka Das Agar Wala Mohila College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Enayetpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('G.D Samsuddin Ahmed Collegiate School and College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Gobra Chandpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Gobra Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Gorai Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Hasimpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Hoshenia Abdul Karim Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Jaduboyra Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Jagannathpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Jagonnathpur Ideal College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Jotmora Junior Girls High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kaliganga Junior Girls School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kallyanpur Junior High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kalowa High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kaya Chield Heaven Girls High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kaya Islamia High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kaya Mahavidyalaya', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Khorshedpur Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Koburat Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kumar Khali Govt. College', 'college', 'public', 'Kushtia', 'Kumarkhali'),
  ('Kumar Khali Islamia Senior Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kumar Khali J.N. Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kumarkhali M.N Pilot High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Kumarkhali Pilot Govt. Girl''s Secondary School', 'school', 'public', 'Kushtia', 'Kumarkhali'),
  ('Kushli Basa Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Madhupur Higher Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Mir Mosarraf Hossain High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Mir Pur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Mohendrapur Darus Sunnah Girls Alim Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Mohendrapur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Naturiya Girls High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('New Model High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Panti College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Panti Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Panti Girls High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Panti Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Pathar Baria Hizlakar Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Pathorbaria Moziber Rahman High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Perfect English Version High School', 'english_medium', 'private', 'Kushtia', 'Kumarkhali'),
  ('Ragib Hasan Technical and Business Management College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Rasulpur Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Robindra Model School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Sadaki Islamia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Sadipurs Secondary School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Saota High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Shadipur Alim Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Shah Mokhdum Mouluk Khorshed (RH) Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Shalghor Modhua Hazi Asia Khatun Secondary Girl''s School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Shelaidah Bisowkabirabindranath Targore College', 'college', 'private', 'Kushtia', 'Kumarkhali'),
  ('Sondah Nondo Pur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Tebaria Sherkandi Girl''s High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('United M.L. High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Uttar Chandpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Uttar Mirpur High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('V.C.D. High School', 'school', 'private', 'Kushtia', 'Kumarkhali'),
  ('Valuka Chowrangi Fazil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kumarkhali'),
  ('Valuka Swahid Shaikh Sadar Uddin Junior Girl''s School', 'school', 'private', 'Kushtia', 'Kumarkhali');

-- ── KUSHTIA SADAR Upazila (115) ─────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Abdalpur Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Adarsha Madhamic Viddalay Kushtia', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Afsar Uddin Mohila Fazil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ail Chara High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ailchara College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Alampur Baliapara Higher Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Alampur Secondary Girls School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Alhaj A. Ghani College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Alhaj A. Ghani Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Arpara Islamia Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Arua Para Girls High School Kustiya', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Bangshitala Shihid Shmriti Junior Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Baradi Secondary Girls School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Barkhada Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Begum Hamida Siddique School and College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Belghoria Rahima Khatun Girls School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Chand Sultana Girls High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Chourhash Mukul Sangha Girls Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Collectorate School and College Kushtia', 'college', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Dahakula Mohammad Shahi Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Darpon Polytechnic Institute', 'polytechnic', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Dinomoni High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Durbachara Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Educare Ideal School and College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('G.K. High School, Kushtia', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Gorai Mohila College Kushtia', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Gorai Survey Engineering Institute, Kushtia', 'technical_school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Goswami Durgapur M/L High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Harinarayanpur Girl''s High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Harinarayanpur M.L. High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Hasan Zaman Lalon Junior High School, Kushtia', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Hasib Dream School College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Horinaraynpur Islamia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Horra Adarsha Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Housing Estat Girls High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Housing Estate Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ibn Sina KG and Junior School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ideal Junior High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Islamic University', 'university', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Islamic University Labratory School and College', 'college', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Isslami Mission School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Jagati High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Jahudia Bazar Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Jhaudia Mahabiddyalya', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Jhugia Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('K.S.M. Dhaka Minapara Higher Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kaburhat High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kalakakali Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kamalapur High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kandarpodia High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Khajanagar Jameya Arabia Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Khater Ali Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Khater Ali Degree College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Khejurtola Patikabari Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Khord Ail Chara Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Khord Ailchara Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kobi Nazrul Academy', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kuatul Islam Kamil Madrasa, Kushtia', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Adarsha Degree College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Government College', 'college', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Govt. Mohila College, Kushtia', 'college', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Institute of Engineering and Technology', 'technical_school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Law College, Kushtia', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Mission Junior High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Polytechnic Institute', 'polytechnic', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Technical School and College, Kushtia', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia City College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia Govt. Central College', 'college', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia Govt. Girls High School', 'school', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia High School and College, Kushta', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia Homioapthic Medical College Kustia', 'medical_college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia Islamia College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kustia Zilla School', 'school', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Lahini High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Luxmipur Hasan Bag Secondary Girls School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Madhu Pur Hodiran Nesa Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Merit Model School, Kushtia', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Mill Para Girl''s High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Mir Abu Abdull Memorial Junior High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Mohammadi Islamia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Mohini Mohan Vidyapith', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Monwara Azmat Ali College, Kustia', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Mrittika Para Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Osman Gani Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('P.T.I. Kustia', 'technical_school', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Pearpur Secondary High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Police Lines School and College', 'college', 'public', 'Kushtia', 'Kushtia Sadar'),
  ('Proteeti School, Kushtia', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Radhanagar Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ranajitpur Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Robindra Maitree University', 'university', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Safina Nursing Institute', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Sahittik Mir Mosharraf Hossain High School, Kushtia', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Sankardia Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Sayed Altaf Hossain Junior Boys High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('School of Laureates International', 'english_medium', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Shaantidanga Misbahul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Shahid Hasan Foiz Girl''s High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Shampur Girls Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Shankardiha Adarsha Mahabiddayalia', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Shirajul Hoque Muslim High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Sunup International School and College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Swastipur Islamia Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Swastipur Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Syed Mas-ud Rumi College', 'college', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Textile Vocational Institute', 'technical_school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('The Old Kushtia High School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ujan Gram Secondary School', 'school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Uzangram Alim Madrasa', 'madrasa', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Ideal Polytechnic Institute', 'polytechnic', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Quamrul Islam Siddique Institute', 'technical_school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Institute of Science and Technology', 'technical_school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia Haji Abul Hossain Institute of Technolgy', 'technical_school', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Lalon University of Science and Arts', 'university', 'private', 'Kushtia', 'Kushtia Sadar'),
  ('Kushtia City Polytechnic and Engineering Institute', 'polytechnic', 'private', 'Kushtia', 'Kushtia Sadar');

-- ── MIRPUR Upazila (82) ─────────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('5 No. Gobindogunia Govt. Primary School', 'school', 'public', 'Kushtia', 'Mirpur'),
  ('A.C. K. Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Abdur Rafet Biswas College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Aburi Magura Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Amla Govt. Degree College', 'college', 'public', 'Kushtia', 'Mirpur'),
  ('Amla Sadarpur Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Anjan Gachi Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Ashan Nagor Anjhuchar Siddikia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Ashannagar High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Atigram Junior Girls High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Atigram Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Azampur High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Bahalbaria Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Balidapara Polytechnic Institute', 'polytechnic', 'private', 'Kushtia', 'Mirpur'),
  ('Balidapara Secondary Girl''s School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Bharol Junior High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Bhedamari Panchbaria Siddikia Alim Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Border Guard Public School and College', 'college', 'public', 'Kushtia', 'Mirpur'),
  ('Boria Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Burhpara Miton Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Chatragacha High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Chhatian Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Chithalia Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Chithalia Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Dangapara Darul Islam Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Dhalsa Payari Hazrat Omar Faruq Dakhil Madrasa', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Dhubail High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Fulbaria High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('G.M.S Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Haji Nurul Islam College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Halsa Adarsha Degree College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Halsa Junior Girls High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Halsa Madehamik Vidyalaya', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Hazrahati United High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Jaharnara Secondary Girls High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('K. M. Ideal College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('K.B.H. High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('K.H.N. Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('K.M. Secondary Girl''s School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('K.N.B Boys High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('K.S.S. Junior High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Kakiladah High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Kamirhat Girls High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Khadimpur Girls High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Kuripole Adarsha Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Kursha K.N High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Kursha M. P. I. Junior Girls School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Kushabaria Charpara Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('L.K.B. Junior High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('M.M. Junior Secondary Girls School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Majihat Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Mashan High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Mir Abdul Karim College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Mirpur Girl''s High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Mirpur Govt. Girls High School', 'school', 'public', 'Kushtia', 'Mirpur'),
  ('Mirpur Junior Secondary Biddya Niketon', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Mirpur Mahmuda Chowdhury College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Mirpur Mohila College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Mirpur Nazmul Ulum Siddiquia Fazil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Mirpur Pilot High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Nawab Sirajuddoula College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Nawda Bahal Baria Adorsha Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Nimtala College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Nimtala Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Nowapara Junior High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Nowda Azampur Technical and Business Management College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Nowdapara Chowduar Secondary Girls School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Paharpur Loxmipur High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Poradah College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Poradaha Girls Secondary School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Poradaha High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('S. N. A. K Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Sadarpur Siddiqia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Sagarkhaly Ideal College', 'college', 'private', 'Kushtia', 'Mirpur'),
  ('Shondah High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Sreerampur Mozaddedia Dakhil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Sultanpur Siddiquia Fazil Madrasah', 'madrasa', 'private', 'Kushtia', 'Mirpur'),
  ('Talbariya High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Teghoria Ideal High School', 'school', 'private', 'Kushtia', 'Mirpur'),
  ('Justice Abu Zafor Siddique Technical Institute', 'technical_school', 'private', 'Kushtia', 'Mirpur'),
  ('Tipu Sultan Institute of Agricultural Technology', 'technical_school', 'private', 'Kushtia', 'Mirpur'),
  ('Justice Abu Zafor Siddique Polytechnic Institute', 'polytechnic', 'private', 'Kushtia', 'Mirpur');
