-- Seed the Bagerhat education institutions list (Bagerhat district only).
-- Source: docs/List of Institutes in Bagerhat.md — a single 571-row table
-- listing every registered school / madrasa / college / technical institute
-- in the district (one row per institution, no per-type grouping). This
-- migration classifies each row by its name and inserts it into the schema.
--
-- Mirrors the Khulna / Satkhira / Jashora seed migrations:
--   * type           — picked from name:
--                       'medical_college'    ← MEDICAL COLLEGE
--                       'polytechnic'        ← POLYTECHNIC
--                       'college'            ← COLLEGE / DEGREE COLLEGE /
--                                              MAHAVIDYALAYA / MAHABIDDALAY /
--                                              LAW COLLEGE /
--                                              SCHOOL AND COLLEGE /
--                                              TECHNICAL (and BM/BM) COLLEGE /
--                                              AGRICULTURE TECHNOLOGY INSTITUTE
--                       'school'             ← any "school"-named entity
--                                              (HIGH / SECONDARY / GIRLS /
--                                              JUNIOR / PRIMARY / ML /
--                                              COLLEGIATE / MODEL / PILOT /
--                                              UCCHA BIDHALAYA / etc.)
--                       'madrasa'            ← MADRASA(H/A/SHA) of any level
--                                              (DAKHIL / ALIM / FAZIL /
--                                              KAMIL / SENIOR / MOHILA /
--                                              BALIKA)
--                       'technical_school'   ← COMPUTER TRAINING CENTRE /
--                                              VOCATIONAL INSTITUTE / PTI
--   * ownership_type — 'public' if the name contains "GOVT"/"GOVERNMENT",
--                      'private' otherwise. Same rule the Khulna seed uses.
--   * city           — always 'Bagerhat'
--   * area           — upazila name, no "Bagerhat" suffix (city already
--                      says Bagerhat, so the picker renders
--                      "<area>, Bagerhat").
--
-- The HTML <br> tags present in the source have been stripped, and any
-- apostrophes doubled for SQL string literals.
--
-- Re-running is safe: the partial unique index
--   (lower(name), coalesce(city, ''), type) WHERE is_active = true
-- dedupes identical active rows.

-- ── Bagerhat Sadar (rows 1–106) ─────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Adarsha Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Al Islah Academy Bagerhat', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Amena Samad Samad Mohila Dhakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Arpara Kurshail High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Arpara Nasaria Siddiquia Dhkhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('B.K.Mandra Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagdia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Sammilani Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Govt. Girls High School', 'school', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Amlapara High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Govt. Mohila College', 'college', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Govt. High School', 'school', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Homoeopathic Medical College and Hospital', 'medical_college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Kamil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Karigori College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Law College, Bagerhat', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat ML High School and College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat P. T. I.', 'technical_school', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagmara Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Baitpur Bhadrapara Jamalia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Baitpur M U High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bara Bash Baria Secondary High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Barui Para Sl. Fazil Madrasah', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Baruipara P C High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Basabati Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bashabati Rahmania High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Belayet Hossain Degree College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bemorta Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bemorta Union High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('BSC High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Chirulia School and College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Chul Kati Ghanashyampur High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Chulkathi Muslima Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Chulkati Ghanashyampur Girl''s High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Dashani Adarsha Secondary Girls School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Dema Karamotia Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Dema Union Kashimpur High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Depara Nesaria Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Fatepur J/R Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Gaon Khali Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Gotapara High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Govt P.C College', 'college', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Govt. Bagerhat Technical School & College', 'college', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Habelee Salehia Dakhil Masrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Hafez Kari Abdus Salam Unani Ayurvedic Medical College and Hospital', 'medical_college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Hakimpur JR Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Hakimpur Shamsul Huda High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Harikhali Purbo Para Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Hazrat Fatema (R) Mohila Technical and Business Management College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Jadu Nath School and College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Jahanabad Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('K J S P U Rajarpur School and College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('K. Hedayetpur Ahmedia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('K.B Fatepur Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('K.M Badokhali Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Kafurpura Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Kandapara N N ML High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Karapar Sart Chandra High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Karapara Secondary Girls School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Karticdia High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Kashimpur Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khan Jahan Ali Degree College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khanjahan Ali Adarsha Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khanjahan Ali Polytechnic Institute', 'polytechnic', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khanjahania High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khanpur Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Kharasambal N.S. High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khegraghat High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Khulna Divisional Physical Education College', 'college', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Kodhla Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Komorpur Secondary Girls School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Sreeghat Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Madhudia Ichca Mayee Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Madinatul Ulum Adarsha Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Mafuja Khanam Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Nowapara Yakub Ali Adarsha High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Pally Unnayan Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Panigahat Islamia Nesaria Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Parkora Mara Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Paschimbhag Belaet Hossain Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Patilakhali High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Rahima Bad Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Rahmatpur Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Rakhal Gasi Darus Sunnah Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Rangdia School and College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Ranjitpur High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Ranobhumi Mirerdanga Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Ronobijoypur High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('S.B. Natoi Khali Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('S.P.C Kafurpura High School and College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('S.S Niketan Khalishpur High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Saira Lakshmi Khali Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Saira Madhudia Collegiate School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Shahid Nayek Abdul Zabbar Secondary School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Shaitgumboj Govt. Primary School', 'school', 'public', 'Bagerhat', 'Bagerhat Sadar'),
  ('Shatgumbaj Bitush Sharaf Adarsha Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Shatgumbaz Technical and Business Management College', 'college', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Sreeghat Sodullapur Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Sugandhi Girls High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Sundarghona High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Syedpur High School', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Textile Vocational Institute', 'technical_school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('U P R Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Uddipan Badar-Shamsu Bidyaniketan', 'school', 'private', 'Bagerhat', 'Bagerhat Sadar'),
  ('Bagerhat Collectorate School and College', 'college', 'public', 'Bagerhat', 'Bagerhat Sadar');

-- ── Chitalmari (rows 107–149) ───────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Bahirdash Mahal Girls High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Barabaria Ideal Commerce College', 'college', 'private', 'Bagerhat', 'Chitalmari'),
  ('Barabaria Jonab Ali Fakir Girls School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Barabaria M. High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Barabaria Rahmania Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Baraguni Meherunnesa High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Boalia Santipur Girls High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Boalia Secondary School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Chaar Kacuria Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Char Baniary Secondary School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Char Bara Baria High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Char Dakatia Secondary School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Charbaniary Nacharia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Charbaniary Union Girls High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Chitalmari Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Chitalmari Hasina Begum High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Chitalmari S. M. Govt. High School', 'school', 'public', 'Bagerhat', 'Chitalmari'),
  ('Dumuria Secondary School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('G.B.D. High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Garibpur Junior High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Govt. Bangabandhu Mohila Degree College', 'college', 'public', 'Bagerhat', 'Chitalmari'),
  ('Hizla High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Hizla Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Kachuria Adarsha High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Kalidas Baral Smriti Mahabidalaya', 'college', 'private', 'Bagerhat', 'Chitalmari'),
  ('Kalshira Rajendra Smriti Secondary School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Kharia Arulia High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Muktabangala Chari Palli High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Naba Palli Ideal High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Nobopalli Junior Girls School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Paranpur Shaheed Sheikh Abu Naser High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Rahmatpur Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Rahmatpur High School and College', 'college', 'private', 'Bagerhat', 'Chitalmari'),
  ('S M Rakbujjaman High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('S. M. Ishaque High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Sabokhali High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Sammilany High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Santikhali Sabuj Sanga High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Santoshpur High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Shaildah Bakpur Karamatia Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Chitalmari'),
  ('Shaildah SESDP Model High School', 'school', 'private', 'Bagerhat', 'Chitalmari'),
  ('Shera Bangla College', 'college', 'private', 'Bagerhat', 'Chitalmari'),
  ('Tripalli Secondary School', 'school', 'private', 'Bagerhat', 'Chitalmari');

-- ── Fakirhat (rows 150–199) ─────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Al-Hera Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Attaka Keramat Ali Pilot High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('B.K.Sk.Ali Ahmed Junior High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Bahirdia High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Banaful Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Bangabandhu Secondary Girls School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Barabaria Lalchandrapur Dhakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Bauidanga (B.L.) Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Betaga Adarsha Girls High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Betaga United M.L. High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Bhabna Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Bhabna Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Chatak Pur S S JR High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Dahar Moubhog Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Deapara Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Dhanpota Maskat United High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Dwadash Palli Secondary Girls School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Fakerhat Sheikh Hasina Technical College', 'college', 'private', 'Bagerhat', 'Fakirhat'),
  ('Fakirhat Fazilatunnesa Mujib Govt. Mohila Degree College', 'college', 'public', 'Bagerhat', 'Fakirhat'),
  ('Fakirhat Karamatia Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Faltita Shashdhar Samaj Kalyan High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Freedom Fighter Dr. Shaikh Boniamin Girls Junior High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Gabkhali Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Hazi A.Hamid Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Hazrat Amir Hamza (R:) Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Jaria Bhattakhamar Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Jaria Islamia Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Kal Kalia G.C. Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Kathali Junior High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Kazi Azhar Ali College', 'college', 'private', 'Bagerhat', 'Fakirhat'),
  ('Khanjahanpur Mohammadia Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Lakhpur Alhaz Ambia Ishak Secondary Girls School and College', 'college', 'private', 'Bagerhat', 'Fakirhat'),
  ('Maskata Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Mouboge Nur Afroj Ali Junior Girls School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Mulghar Govt. High School', 'school', 'public', 'Bagerhat', 'Fakirhat'),
  ('Mulghar Girls'' High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Naldh Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Piljanga Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Quazia Azher Ali Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Sakina Azher Technical College', 'college', 'private', 'Bagerhat', 'Fakirhat'),
  ('Sammiloni Junior High School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Shah Auliabag M M Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Shaheed Smriti Degree College', 'college', 'private', 'Bagerhat', 'Fakirhat'),
  ('Sheikh Abu Bakar Siddique Aminia Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Sheikh Helal Uddin Govt. College', 'college', 'public', 'Bagerhat', 'Fakirhat'),
  ('Shirin Haque Pilot Girls Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Shubhadia K.B. Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat'),
  ('Syed Mohalla K K Govt Girls High School', 'school', 'public', 'Bagerhat', 'Fakirhat'),
  ('Tekatia Deapara Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Fakirhat'),
  ('Tekatia Secondary School', 'school', 'private', 'Bagerhat', 'Fakirhat');

-- ── Kachua (rows 200–229) ───────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Akhteruddin Memorial High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Andhar Manik High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Andharmanik Girls High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('B. C. Vasha High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Baruikhali High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('C.S. Pilot Govt. Model High School', 'school', 'public', 'Bagerhat', 'Kachua'),
  ('Char Sonakur Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Dhopakhali Secondary School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Gazalia Ideal High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Gazalia Rahmania Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Goalmath Rashiklal Secondary School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Goalmath Secondary Girl''s School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Govt. Shohid Shaikh Abu Nasser Mohila Degree College', 'college', 'public', 'Bagerhat', 'Kachua'),
  ('Jobai Adarsha High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Kachua Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Kachua Degree College', 'college', 'private', 'Bagerhat', 'Kachua'),
  ('Kachua Pilot Girls School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Madhabkathi Ahmadia Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Maghia Salehia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Majeda Begum Krishi Projukti College', 'college', 'private', 'Bagerhat', 'Kachua'),
  ('Masni Secondary School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Mobaidul Islam Secondary School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Nurjahanpur Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Padma Nagar Junior High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Saheed Asad Smriti High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Sangdia Adarsha Junior School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Shahid Abdul Jalil High School', 'school', 'private', 'Bagerhat', 'Kachua'),
  ('Shoheed SK Fazlul Haque Moni Tech. & College', 'college', 'private', 'Bagerhat', 'Kachua'),
  ('Shonakur Girls Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua'),
  ('Tengrahkali Hossainia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Kachua');

-- ── Mollahat (rows 230–265) ─────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Khalilur Rahman College, Mollahat', 'college', 'private', 'Bagerhat', 'Mollahat'),
  ('A.S.S.M. High School (Singati)', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Bhanderkhola Junior Girls High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('C.S. Technical and B.M. College', 'college', 'private', 'Bagerhat', 'Mollahat'),
  ('Chander Hat Girls High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Chanderhat High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Charkulia Girls High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Charkulia High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Charkulia Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mollahat'),
  ('Chaultury High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Dariala Kachna Kushla Secondary School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Dattadanga A.C. Secondary Academy', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Dr. Monsur Ahmad High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Gangni High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Ghoshgati Dr Hemayet Uddin Secondary Girls School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Girishnagar Garfa Secondary High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Jatir Janak Bangabandhu Woman College', 'college', 'private', 'Bagerhat', 'Mollahat'),
  ('K.N.A.S.A Hamid High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Kachuria Bazar Hazi Saber Molla Memorial Secondary School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Kahalpur Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mollahat'),
  ('Kamar Gram Secondary School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Kamargram Jatir Janak Bangabandhu S K Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mollahat'),
  ('Kodalia High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Kodalia M.H.B. Junior Girls High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Laila Azad Degree College', 'college', 'private', 'Bagerhat', 'Mollahat'),
  ('Lutfor Rahman Business Management College', 'college', 'private', 'Bagerhat', 'Mollahat'),
  ('Nagarkandi Sapta Palli Secondary School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Nashukhari Social Welfare High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Noor Jahan Mohila BM College', 'college', 'private', 'Bagerhat', 'Mollahat'),
  ('Nutan Ghoshgati Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mollahat'),
  ('Rajpat Sharulia Akbaria Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mollahat'),
  ('Sachiadah Chukhola M.B. Secondary School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Satya Shiksha Niketan (Junior)', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Shaheed Hemayet Uddin Girls High School', 'school', 'private', 'Bagerhat', 'Mollahat'),
  ('Wazed Memorial Govt. Model High School', 'school', 'public', 'Bagerhat', 'Mollahat'),
  ('Tetulbari M M Obaydur Rahman Secondary School', 'school', 'private', 'Bagerhat', 'Mollahat');

-- ── Mongla (rows 266–314) ───────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Al Hazz Shaikh Afsar Uddin Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Al-Haz Korban Ali Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Amratala Chapra Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Arazee Makordhon Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Aziz Bhatti High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('B N School and College, Mongla', 'college', 'private', 'Bagerhat', 'Mongla'),
  ('Bangabandhu Mohila Govt. College', 'college', 'public', 'Bagerhat', 'Mongla'),
  ('Burburia High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Burir Danga Secondary Girls School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Burirdanga Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Chalna Bandar Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Chalna Bandar Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Chandpai Mesershah Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Chandpai Pir Meser Shah Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Chila Manu Mia High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Chowri Danga Ahmadia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Creative Computer Training Centre', 'technical_school', 'private', 'Bagerhat', 'Mongla'),
  ('Dakhin Chila Siddikia Ahmadia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Digraj Degree Mahavidyalaya', 'college', 'private', 'Bagerhat', 'Mongla'),
  ('Digraj High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Digraj Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Dock Sramic High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Eunus Ali Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('G M S High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Govt. Mongla College', 'college', 'public', 'Bagerhat', 'Mongla'),
  ('Govt. T A Faruque School and College', 'college', 'public', 'Bagerhat', 'Mongla'),
  ('Haldibunia High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Islami Adarsha Academy Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Ismail Memorial High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Joymoni Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Khaserdanga A B S Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Kochubunia Darus Sunnat Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Madur Palta Neaz Makhdum Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Malgazi Girls High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('MD Ismail High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Memory Computer Proshikhkon Academy', 'technical_school', 'private', 'Bagerhat', 'Mongla'),
  ('Mohsina Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Mongla Bandar Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Mongla Girls High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Mongla Technical and Business Management College', 'college', 'private', 'Bagerhat', 'Mongla'),
  ('Sabed Kahn Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Santimayee Junior Girls High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Sheikh Fazilatunnesa Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('Sheria Begum Secondary Girls School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Sonail Tala A B S Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Mongla'),
  ('St Pauls High School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Tatibunia Secondary School', 'school', 'private', 'Bagerhat', 'Mongla'),
  ('Uttar Banshtala Govt. Primary School', 'school', 'public', 'Bagerhat', 'Mongla'),
  ('Mongla Govt Technical School College Mongla Bagerhat', 'college', 'public', 'Bagerhat', 'Mongla');

-- ── Morrelganj (rows 315–461) ───────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Sreeni Khali Ishaq Ali Smritti Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('34No. Jilbunia Kamla Govt. Primary School', 'school', 'public', 'Bagerhat', 'Morrelganj'),
  ('A R Khan College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('A.B. Gozalia Hazi Mahir Uddin Smriti Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('A.C. Laha Pilot High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('A.G. Makbul Hosshen B.D. Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Abdul Aziz Memorial High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Abuhurairah Adarsha Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Alokito Bangladesh Technical and B.M College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Amtoli Islamia Kamil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('B S Rahmatia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('B S Wahezia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('B.B Afsar Ali High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('B.K High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('B.P.G.M. Rahmania High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('B.S.S. Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Badni Vanga Adarsha Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Badurtala Chowdugor Fakirbari Dhakil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Bage Jannat Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Bahar Bunia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Baharbunia High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Balaibunia Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Banagram Century Institution', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Bathkashe High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Begum Meherunnesa Mahila Mahabiddalay', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Bipin Kamal Junior Girls School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('BK Gilbunia Ahmadia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Boropari Junior Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Char Hoglabunia Azizia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Charhogla Bunia Momin Smriti High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Chhaprakhali Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Chingra Khali Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Chipa Baraikhali High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Daibajna Hati B.M. High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Daibajnahati Adarsha Girls High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dakhin Sutalori Monir Uddin Dhakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dakshin Bangla College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dakshin Sutalari H.M.J.K.M. Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Darul Quran Fazlul Karim Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Darul Quran Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Deuatala K C Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dhansagar Pallimgal Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dharadoa Multilateral High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dhuligati M.T. High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('DK M Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dr. Hiranmoy Halder Technical & B.M College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dr. Mozammel Hossain Agriculture Technology Institute', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dr. Khalilur Rahman College, Morrelganj', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Dr. Miah Abbasuddin Teachers Training College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Enaytia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Fakirbari Adarsha High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Fulhata Fazlul Karim Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Fulhata High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('G B Amena Khatun Balika Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Ghasiakhali Islamia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Goalbaria A.K. Smriti Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Golbunia Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Govt. Sirajuddin Memorial College', 'college', 'public', 'Bagerhat', 'Morrelganj'),
  ('Gulisha Khali Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Gulishakhali R M High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Gulzia Islamia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('H.V.S Hazi Nuruddin Dhakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Habibullah Abad Islamia Siddikia N.S. Kamil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hamcapur Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hamejia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hartakitala Urful Smriti High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hazi Ibrahim S. R. Rahmania Dhakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hazi Rajaullah Smrity High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hogalpati High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hoglabunia Lehazuddin Erfania Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Hoglapasha Govt. Primary School', 'school', 'public', 'Bagerhat', 'Morrelganj'),
  ('J.S Patjuria H.A. Balika Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Janashakti Secondary Girls School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Jewdhara Moulavibazar Nesaria Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Jiudhara Serjan Smriti Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('K K Poler Hat High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('K M Boulpur Islamia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kachu Bania Hashem Ali Girls High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kachubunia Rahmatia High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kadam Rasularpar Lehazuddin Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kathaltala Giashia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Khadiza Begum Junior High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Khanirkhanda S-I Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kharaikhali Jahura Jr. Girls School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kharikhali Ahamadia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Kuhardah R.A.M. Multi Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Ma Babar Rain College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Manik Mia Girls Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Monoara Begum Islamia Mohela Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Morrel Gong K.G High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Morrel Gonj Govt. Girls High School', 'school', 'public', 'Bagerhat', 'Morrelganj'),
  ('Morrelganj Town High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Morrelgonj Latifia Kamil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Nehal Khali Girls High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Nehalpur Kuhardha Dhakil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Network Computer Training Institute', 'technical_school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Nishanbaria Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Olagonj N.U. Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Panch Gaon M.M. Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Panchagram Sammilithad Yeesufia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Panchokaron Siraj Smriti Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Parkumar Khali High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Polerhat Alhaz Azharia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Purba Chandipur Girls High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Putia Adarsha Balika Madhyamik Vidyyalaya', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Putikhali Islamia Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Putikhali Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Rajoir Nesaria Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Rawshan Ara Girls High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Rawshanara Memorial Women Degree College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('S Chandipur Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('S. P Rashida High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('S.B. Adarsha Multilateral High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sabera Ferdosi Secondary Girls School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Salimabad Degree College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Salimgor Chinrakhali Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sammilani Secondary Shiksha Niketan', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sammilani Uchcha Balika Vidyyalaya', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sannaysi Barisal Latifa Dakhil Maderasha', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sannyasi Secondary Girl''s School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Setara Abbas Technical and Business Management College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Setara Abbas Technical and B.M College Junior School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Shahid Sheikh Rasel Mujib High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Shahid Smriti Uchcha Bidyalaya', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Singjor Gopalpur S. Girl''s High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Singjore Chandipur Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Singjore Gopalpur College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('Somadar Khali Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sonakhali P.K Mohsenia S. Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sonakhali Azizia Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sonakhali Mahabbat Ali Secondary School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sonakhali Technical & B.M. College', 'college', 'private', 'Bagerhat', 'Morrelganj'),
  ('South Jamirtala G. H. Nurul Islam Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('South Taligati Darulhuda Saheia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Sree Sree Gopal Chand High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Suhasini High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Suprakhali Gazir Ghat Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Surendra Nath Smriti Girls High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Surjya Mukhi Halder Bari Girls Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Suttalory Sofizuddin Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Talimunnesa Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Tofael Uddin Sriti Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Torab Memorial High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Tuzamber Ali High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Uttar Sutalari High School', 'school', 'private', 'Bagerhat', 'Morrelganj'),
  ('Utter Putikhali Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Morrelganj'),
  ('Mosharrof Hossain College', 'college', 'private', 'Bagerhat', 'Morrelganj');

-- ── Rampal (rows 462–528) ───────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Abubakar Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Adaghat High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Al Haz Sufia Brgum Mohila Dhakil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Amtala Junior High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Baintala Chasree Nesarea Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Baintala Kashipur High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Baintala Union Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Barakatali ML. High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Baruepara Zulfikaria Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Bastali High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Bastali Pally Unnayan Junior High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Betkata High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Betkata Union Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Bhuciar Kandar High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Biswashuk Secondary Biddyapith', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Borni Sairabad ML. High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Borni Sairabad Quinton Girls High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Chaksree Akubaria Bree Chaksree Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Chanditala United High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Chandpur Shankar Nagar Jr. High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Chhota Sannyashi Junior High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Dakra Multilateral High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Fatimatuzzohura R Mahila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Foyla Hat Asia Karmatia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Foylahat Kamal Uddin Madhyamik School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Gafur Memorial Junior High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Gilatala Abul Kalam College', 'college', 'private', 'Bagerhat', 'Rampal'),
  ('Gilatala ML. High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Gobindapur A.J.S. Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Hazi Enayet Ullah Dakhail Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Hazi Arif Girls High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Hurka Jhalmalia Shelika Junior Girls High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Hurka Sitanath Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Islamabad Siddiqua Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Jhanjhania High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Jhanjhania Siddiqia Dhakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Joynagar Pipul Bania Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Kadir Khola High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Kalekharber Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Khanjahan Ali High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Khejur Mahal T.R. Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Kumalai Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Kumlai Salehia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Madardia Adarsha Junior High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Malliker Ber Senior Fazil Amderasha', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Mallikerber Model High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Pabantala Girls High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Perikhali Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Perikhali Model High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Rajnagar Union Junior Girls School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Rampal Govt. Degree College', 'college', 'public', 'Bagerhat', 'Rampal'),
  ('Rampal Pilot Girls High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Saguna Secondary School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Sannyasi School and College', 'college', 'private', 'Bagerhat', 'Rampal'),
  ('Sharafpur Karamatia Senior Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Sonatunia A.K. Junior Girls High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Sonatunia Azizia Kamil (M.A) Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Sreefaltala Pilot High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Sundarban Mohila College', 'college', 'private', 'Bagerhat', 'Rampal'),
  ('Sundarpur Junior High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Taterhat Junior School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Tulshirabad K.U.M. High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Ujalkur Girls JR High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Ujalkur High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Vekatmary Belai High School', 'school', 'private', 'Bagerhat', 'Rampal'),
  ('Ziolmari Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal'),
  ('Dr Forhad Hossain Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Rampal');

-- ── Sarankhola (rows 529–571) ───────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Akandapara Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Amena Memorial Girls Junior High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Amragachhia Multilateral High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Anowar Hossain Secondary School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Ashraful Kalam Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('B. K. Junior Secondary Girls School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Badhal Idel Secondary School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Bara Rajapur Salehia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('D.N. Akata Junior Girls High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Dakkhin Rajapur Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Dhansagar Nalbunia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Dhansagar Radhalaxmi Junior Girls High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Dhansagar United High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Dhansagor Nalbunia Govt. Primary School', 'school', 'public', 'Bagerhat', 'Sarankhola'),
  ('Dhansagor Rajapur Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Dr. Masum Billah D.N. Technical College', 'college', 'private', 'Bagerhat', 'Sarankhola'),
  ('Janata High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Kadamtala Mohsinia C. H. K. Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Khada Alhaz Gagon Mamoreal Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Khonta Kata Secondary School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Khontakata Mofidia Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Khontakata Union Secondary School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Kohinur Haque Womens Technical and BM College', 'college', 'private', 'Bagerhat', 'Sarankhola'),
  ('Madinatul Ulum Latifia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Matree Bhasha College', 'college', 'private', 'Bagerhat', 'Sarankhola'),
  ('Muktijodda Mofizul Haque Krishi Projukti and Vocational Institute', 'college', 'private', 'Bagerhat', 'Sarankhola'),
  ('R. K. D. S. Pilot Girls High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Rajapur Girls High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Rajapur High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Rasulpur Junior High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Rayenda Bazar Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Rayenda Darul Hedayet Nesarul Ulum Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Rayenda Govt. Pilot High School', 'school', 'public', 'Bagerhat', 'Sarankhola'),
  ('Rayenda Rajoir Fazil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Sadik Computer Training Institute', 'technical_school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Sarankhola Govt. Degree College', 'college', 'public', 'Bagerhat', 'Sarankhola'),
  ('Sarankhola Ideal Institute', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Sharokhola Mohila Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Sonatala Islamia Alim Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('South Khali Junior Secondary Girls School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Sundarban Islamia Dakhil Madrasa', 'madrasa', 'private', 'Bagerhat', 'Sarankhola'),
  ('Sundarbon High School', 'school', 'private', 'Bagerhat', 'Sarankhola'),
  ('Tafal Bari School and College', 'college', 'private', 'Bagerhat', 'Sarankhola');
