-- Seed the Magura education institutions list (Magura district only).
-- Source: docs/List of Institutes in Magura.md — a single 303-row table
-- listing every registered institution in the district (one row per
-- institution, no per-type grouping). This migration classifies each row
-- by its name and inserts it into the schema.
--
-- Mirrors the Bagerhat seed (same single-table format, same rules):
--   * type           — picked from name:
--                       'medical_college'    ← MEDICAL COLLEGE
--                       'polytechnic'        ← POLYTECHNIC /
--                                              COLLEGE OF ENGINEERING AND TECHNOLOGY
--                       'college'            ← COLLEGE / DEGREE COLLEGE /
--                                              MAHAVIDYALAYA / MAHABIDDYALA /
--                                              SCHOOL AND COLLEGE /
--                                              TECHNICAL (and BM) COLLEGE /
--                                              TEACHERS TRAINING COLLEGE /
--                                              KRISHI COLLEGE / NURSING INSTITUTE
--                       'school'             ← any "school"-named entity
--                                              (HIGH / SECONDARY / GIRLS /
--                                              JUNIOR / PRIMARY / COLLEGIATE /
--                                              MODEL / PILOT / PREPARATORY /
--                                              INSTITUTE etc.)
--                       'madrasa'            ← MADRASA(H/A/SHA) of any level
--                       'technical_school'   ← COMPUTER TRAINING CENTRE /
--                                              VOCATIONAL INSTITUTE / PTI
--   * ownership_type — 'public' if the name contains "GOVT"/"GOVERNMENT",
--                      'private' otherwise. Collectorate and Police Lines
--                      institutions are also flagged public.
--   * city           — always 'Magura'
--   * area           — upazila name, no "Magura" suffix.
--
-- HTML <br> tags stripped, names cleaned, apostrophes doubled for SQL.
-- Re-running is safe: the partial unique index
--   (lower(name), coalesce(city, ''), type) WHERE is_active = true
-- dedupes identical active rows.

-- ── Magura Sadar (rows 20727–20849) ──────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('A. Mozid Academy Greehogram', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('A. N. Sammiloni Girls High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Abal Pur High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Adorsha Shammiloni Secondary Girls School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Aisa Womens College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Al Amin Trust Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Al-Amin Technical and Business Management College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Alaipur Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Alhaz Kazi Abdul Wahed Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Alokdia Pukhariya Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Amoresh Bosu Degree Mohabidayalaya', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Amuria Junior High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Amuria Technical and Business Management College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Arayshata Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Baghdanga Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Baharbag Abedali Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Baharbag Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Baitush Salam Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Banassree Rabindra Smarani College Krishnabila (Tangakhali)', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Barashalai Pancha Palli High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Barashia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Belnagar High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Benga Beroil Junior Girls School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Beroil Bazar Higher Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Beroil Darul Huda Senior Fazil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Beroil Poilita Girls High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Beroil Samsuddin Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Bhabon Hati High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Bogia Subhashine Basu High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Bogura High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Bogura Mazail Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Buzruk Sree Kundi College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Buzruk Sree Kundi Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Buzruk Srikundi M.A. Hamid High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Chandpur Govt. Primary School', 'school', 'public', 'Magura', 'Magura Sadar'),
  ('Chitra Computer Training Centre', 'technical_school', 'private', 'Magura', 'Magura Sadar'),
  ('Choto Joka Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Chotofalia High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Dakhin Mirzapur Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Dakhin Nowapara Sammilani College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Dhalahara Chandpur Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Dhalhara West Para Girls School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Dhon Para Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Dorah Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Excel Computer Training Centre', 'technical_school', 'private', 'Magura', 'Magura Sadar'),
  ('Fulbari H. M. R. Junior High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Gangnalia High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Goalbathan High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Govt. H.S.S. College, Magura', 'college', 'public', 'Magura', 'Magura Sadar'),
  ('Hazipur Sammilani College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Hazipur Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Hazrat Peer Mukarram Ali Shah (R) Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Ichakhada S.A.M. High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Islami Technical and Vocational Institute', 'technical_school', 'private', 'Magura', 'Magura Sadar'),
  ('Jagdal Sammiloni College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Jagdol Rupati Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Jagla Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Jagla H.M. High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Jogdal Adarsha Junior Girls School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Jogdal Sammiloni High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('K.S. Darul Quran Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Kapashati Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Kashbon Polytechnic Institute, Magura', 'polytechnic', 'private', 'Magura', 'Magura Sadar'),
  ('Kasundi High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Katakhali High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Kuchiamora Girls High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Kullia Kuchiamora Syed Ator Ali Higher Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Lakshmipur Bazar High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Madhabpur Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Technical School and College, Magura', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Magura A.G. Academy', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Adarsha Girls High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Adasha Degree College Magura', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Collectorate Collegiate School', 'school', 'public', 'Magura', 'Magura Sadar'),
  ('Magura College of Engineering and Technology', 'polytechnic', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Dudh Mallik Secondary Girl''s School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Govt. Girls High School', 'school', 'public', 'Magura', 'Magura Sadar'),
  ('Magura Govt. High School', 'school', 'public', 'Magura', 'Magura Sadar'),
  ('Magura Govt. Mohila College', 'college', 'public', 'Magura', 'Magura Sadar'),
  ('Magura Ideal Technical and Business Management College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Polytechnic Institute', 'polytechnic', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Siddiquia Kamil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Stadium Para Girls'' Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Magura Teacher''s Training College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Malanda Panchaboti Girls High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Malunchi Secondary High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Mirzapur Girls High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Momotaj Shirin Abul Kashem Junior Secondary Institute', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Monoara Zaman Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Musapur Gobindopur Hossenia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Nanduali D.U. Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Nazir Ahamad Degree Mahavidaloy', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Nischintapur Junior High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Nursing Institute Magura', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Pakakanchan Pur Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Parnandual High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Parpalita P.P.N.C. High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Pashchim Bariala Sirajul Islam Junior School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Patokhali Sammiloni Girl''s High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Perfect Education Junior Girls School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Police Lines High School Magura', 'school', 'public', 'Magura', 'Magura Sadar'),
  ('Presidency Institute of Technology', 'polytechnic', 'private', 'Magura', 'Magura Sadar'),
  ('Primary Teachers'' Training Institute, Magura', 'technical_school', 'public', 'Magura', 'Magura Sadar'),
  ('Profulla Singha Ayurvedic Medical College', 'medical_college', 'private', 'Magura', 'Magura Sadar'),
  ('Pukhoria Alokdia Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Pukuria Alokdia Secondary Girls School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Raghaab Dair High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Ramnagar H.P. High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Rawtara H.N School and College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Sammilony Bahumukhy Alim Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Satrujitpur Abdul Gani Secondary Girl''s School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Satrujitpur K.P. Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Satrujitpur Nurul Islam Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar'),
  ('Sattyapur ML. High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Shatrujitpur College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Shibrampur High School and College', 'college', 'private', 'Magura', 'Magura Sadar'),
  ('Shuvechchha Preparatory School, Magura', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('South Nawpara Sammilani High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('SP Computer Proshikhkhon Institute, Magura', 'technical_school', 'private', 'Magura', 'Magura Sadar'),
  ('Sree Kundi Secondary School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Srirampur High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Titar Kha Para High School', 'school', 'private', 'Magura', 'Magura Sadar'),
  ('Uttar Bir Pur K.Monsi Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Magura Sadar');

-- ── Mohammadpur (rows 20850–20921) ──────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Aminur Rahman College, Mohammadpur', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Babu Khali Adarsha College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Babukhali Aptab Uddin Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Babukhali Islamia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Babukhali Junior Girls School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Balidia Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Balidia Adarsha Mohil Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Balidia Mazharul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Baniabahu Kawra Quaderia S.R. Alim Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Basho Machinagra Junior School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Basur Dhuljuri High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Bhethulia Girls School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Binodpur Degree College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Binodpur B. K. High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Binodpur Nanibala Girls High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Binodpur Shaju Bibi Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Biren Sikder Ideal High School and College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Bongram K.M.S. Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Bororia A.W. Senior Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Chakulia S M Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Chalima Girls Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Chittabisram Govt. Primary School', 'school', 'public', 'Magura', 'Mohammadpur'),
  ('Chotokalam Dhary Darussunna Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Chowbaria High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Dhoail Adarsha Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Dhulajora Churargati P. C. High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Digha Intaz Molla High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Dumurshia D.C. ML. High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Ghullia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Gopal Nagar Junior High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Gopinathpur M. A. Khaleque Secondary School and College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Govt. Bir Muktijoddha Asaduzzaman College', 'college', 'public', 'Magura', 'Mohammadpur'),
  ('Harekrishna Pur M F A Girls High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Hazi Mosleim Uddin Technical and BM College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Horekrishno Pur Junior High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Jessobanto Pur High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Jhamah Barkatul Ulum Senior (Fazil) Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Jhama High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Joshpur Mohila Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Joyrampur Shapta Gram Shammelony Junior High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Kalisonkorpur High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Kanutia A. Ala Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Kashipur Shindain Gurosthan Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Kazi Salima Haque Mohila Degree College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Kerinagar S S Junior Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Khali Sha Khali High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Khalia High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Kumrul High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Mandarbaria Madenatul Aulia Oal Olama Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Mohammad Pur Borkotia S.A.R Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Mohammadpur Adarsha Technical and B.M College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Mohammadpur Girls High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Monoara Zaman Krishi College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Mousha Mohammadia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Nagripura Islamia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Narail Magura Ideal Technical and Business Management College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Nohata A.G Fazil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Nohata Collegiate Girl''s School and College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Nohata Rani Patit Paboni High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Palash Baria High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Palla Secondary Girls School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Pallabahumukhi School and College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('R.S K.H Institution Govt. Model Secondary School', 'school', 'public', 'Magura', 'Mohammadpur'),
  ('Rajapur Secondary Girls High School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Rajpat Rajapur R M A Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Rajpat Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Rarikhali Secondary School', 'school', 'private', 'Magura', 'Mohammadpur'),
  ('Rizia Rubia Mohila Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Mohammadpur'),
  ('Talla Baria S.N. Technical School & BM College', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Tallabaria SN Krishi Projukti Institute', 'college', 'private', 'Magura', 'Mohammadpur'),
  ('Mohammadpur Government Technical School and College', 'college', 'public', 'Magura', 'Mohammadpur'),
  ('Mohammadpur City School and College', 'college', 'private', 'Magura', 'Mohammadpur');

-- ── Shalikha (rows 20922–20980) ─────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Amian High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Amjad Ali Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Arpara Degree College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Arpara Ideal Govt. Model High School', 'school', 'public', 'Magura', 'Shalikha'),
  ('Arpara Mohila College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Arpara Sadar Alim Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Arpara Secondary Girls School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Avoya Charan High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Bagdanga Shamsul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Baulia Nirod Krishna Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Bhul Baria High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Biharilal Shikder Govt. Mahabiddyala', 'college', 'public', 'Magura', 'Shalikha'),
  ('Bolai Naghosha Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Bunagati Degree College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Bunagati Secondary Girls School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Chandara Pragati Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Chaturbaria High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Chhayghoria A B S Fazil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Dakhan Sharu Shoona Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Dhaneswr Gati High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Gangaram Pur Girls High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Gangarampur P.K. Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Garerhat Kazi Aysa Khatun Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Gobra Panchapolly High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Gongarampur Shadria Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Harishpur Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Hazrahati Sammiloni College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Junary Khadizatul Kubra (R:) Darul Ulum Mohila Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Katali High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Khator Ramanondokati High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Kotvag Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Kumar Kota Alim Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Magura Krishe Institute', 'college', 'private', 'Magura', 'Shalikha'),
  ('Mashakhali Dadal Palli A Goni Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Modhukhali Aminia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Munshi Shohidur Rahaman BM College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Naghosa Nabam Polli High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Naghosha Ideal Girls High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Pear Pur Islamia Girls Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Piprul Abdul Hakim Mollick Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Poragachi Saptalli Jr. Girl''s School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Pulum Golam Sarwar Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Pulum Qazi Saleema Haq Secondary Girls School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Sandara Madinatul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Saraswatee Shikdar Girl''s School and College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Satakhali Darul Ulum Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Satakhali High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Shakila Ideal Technical B.M College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Shalikha Thana High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Sharushoona Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Sharushuna Adarsha Secondary School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Sheojgati Adorsho Secondary Girls School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Shimakhali School and College', 'college', 'private', 'Magura', 'Shalikha'),
  ('Singra Tilkhari ML. High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Srehatto High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Talkhari High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Thaipara High School', 'school', 'private', 'Magura', 'Shalikha'),
  ('Uttor Sharushuna Usufia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Shalikha'),
  ('Shalikha Government Technical School and College', 'college', 'public', 'Magura', 'Shalikha');

-- ── Sreepur (rows 20981–21029) ──────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Takhalpur Hatem Ali Mia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Amalsar Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Amtoil High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Amtoil J.T.S. Kaderia (R:) Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Badanpur Adarsha Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Bakhera Mokordom Khola Junior School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Bangabandhu Govt. College, Sreepur, Magura', 'college', 'public', 'Magura', 'Sreepur'),
  ('Barishat Purbapara Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Barishat Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Bilsonai High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Char Maheshpur Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Chargoalpara Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Chougachi High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Dariapur Degree College', 'college', 'private', 'Magura', 'Sreepur'),
  ('Doran Nagar High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Dr. Nurul Hossain Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('G.K Ideal Degree College', 'college', 'private', 'Magura', 'Sreepur'),
  ('Hat Dariapur Sammilani Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Jaria Sammilani High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Kadir Para Sammiloni Islamia Alim Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Kajoli Collegiate School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Kalinagar High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Kazoli Islamia Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Khamar Para Siddikia Ahammadia Islamia Alim Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Khamarpara Pilot Secondary Girls School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Khamarpara Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Langalband Darul Islam Siddikia Senior Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Langolbandh High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Madanpur Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Modhupur Radha Charan Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Nabagram Kabir Ahmmad Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Nabagram Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Nakol Raicharan Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Nakol Sammiloni Degree College', 'college', 'private', 'Magura', 'Sreepur'),
  ('Nohata Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Panchapally Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Radha Nagar Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Rajapur Durgapur Sammilita Dakhil Madrasa', 'madrasa', 'private', 'Magura', 'Sreepur'),
  ('Raynagor Sunrise Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Sabdalpur Union Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Sammilita Pancha Gram Girl''s High School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Sarongodia A.Mojid Joarder Secondary Girls School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Shankar Vedanta Math Mission Secondary Girls School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Sreekole Secondary School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Sreepur Govt. Degree College', 'college', 'public', 'Magura', 'Sreepur'),
  ('Sreepur M.C. Pilot Govt. Secondary School', 'school', 'public', 'Magura', 'Sreepur'),
  ('Sreepur Mohila College', 'college', 'private', 'Magura', 'Sreepur'),
  ('Sreepur Secondary Girls School', 'school', 'private', 'Magura', 'Sreepur'),
  ('Tikerbila Secondary School', 'school', 'private', 'Magura', 'Sreepur');
