-- Seed the Jhenaidah education institutions list (Jhenaidah district only).
-- Source: docs/List of Institutes in Jhenaidah.md (a single mixed table —
-- every row classified by name into one of the schema enums).
--
-- Mirrors the Khulna / Satkhira / Jashore / Bagerhat / Magura / Narail /
-- Kushtia / Chuadanga / Meherpur seeds:
--   * type           — 'university' for universities (none in this district),
--                      'medical_college' for medical colleges (none in this
--                      district), 'polytechnic' for polytechnic institutes
--                      (Jhenaidah Polytechnic Institute, Srizony Polytechnic
--                      Institute, Novel Polytechnic and Textitle Institute),
--                      'college' for any degree / higher-secondary college
--                      (incl. mohabiddalaya / mahabiddalay, technical
--                      school-and-college, business management college,
--                      school-and-college, model college, nursing/health
--                      college, cadet college, law college, teachers training
--                      college), 'madrasa' for dakhil / alim / fazil / kamil
--                      / darul ulum / senior / islah / alhera madrasas, plus
--                      Islami/Islamia integrated institutes treated like
--                      madrasas (Al Hera Islami Institute, Ashan Nagar
--                      A.B.C.D Alim Madrash, etc.), 'technical_school' for
--                      free-standing technical / vocational / computer
--                      training centers / science & technology institutes /
--                      medical technology institutes / veterinary training /
--                      agriculture training institutes / technical colleges,
--                      'school' otherwise (incl. Academy, Bidya Niketon,
--                      Biddyapith, Junior School, Collegiate School, Pilot
--                      Schools without Govt prefix, Viddya Niketan).
--   * ownership_type — 'public' for "Govt." / "Government" institutions and
--                      for institutional entities run by the state
--                      (Collectorate, Police Lines, P.T.I. — Primary
--                      Teachers' Training Institute, Cadet College).
--                      Note: the Jhenaidah Cadet College is one of 12
--                      government cadet colleges in Bangladesh.
--                      "Pilot" without "Govt" stays private.
--   * city           — always 'Jhenaidah' (the picker filters by this column
--                      when the student picks Jhenaidah as their district)
--   * area           — upazila name (no "Jhenaidah" suffix, since city
--                      already says Jhenaidah).
--
-- Source-quality notes (kept as-written for traceability):
--   * "<br>" tags inside names are stripped.
--   * Apostrophes inside names are doubled for SQL ("GIRL'S" → "GIRL''S").
--   * Multiple consecutive spaces collapsed to one.
--   * Typographic typos preserved (e.g. "BIDDYAPITH"/"BIDDYAPIT",
--     "MOHABBIDDALAY", "TRANNING", "MADRSHA", "MADRASH", "SHAHAR BATI",
--     "SHOOL"/"SCHOL"/"SCOOL", "MAHTAB", "SECOUNDARY", "SECOHDARY",
--     "HOSSAIN"/"HOSSIAN"/"HOSSAN", "CORMULA", "MONOHARPUR",
--     "B.E.S.E."-style initialisms, "MUTALEB", "HAZRAT", "FURSHONDI").
--     Easy to normalise in a follow-up if desired.
--
-- Re-running is safe: the partial unique index
--   (lower(name), coalesce(city, ''), type) WHERE is_active = true
-- dedupes identical active rows.
--
-- Upazila row counts:
--   * HORINAKUNDA     — 56
--   * JHENAIDAH SADAR — 139
--   * KALIGANJ        — 89
--   * KOTCHANDPUR     — 42
--   * MAHESHPUR       — 83
--   * SHAILKUPA       — 91
--   * Total           — 500

-- ── HORINAKUNDA Upazila (56) ─────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Andulia High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Backchua Laxhipur High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Balarampur Darus Sunnah Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Bangabondhu Biggan and Beboshay Babostapona College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Bhahbnipur High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Bhaina Shahid Mosaraf Dalil Uddin High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Bhalki High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Bhaturia Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Bherakhali High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Chandpur High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Char Aruakandi Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Charatala Adarsha Junior Girls High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Charumonnesa Girls Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Dakhalpur Siddikia Fazil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Daribinni Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Dhulia Adarsho High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Durlabpour High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Falshi Secondary High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Garabaria Siddikia Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Ghoragachha Lal Mohammad High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Govt Lalon Shah College, Horinakunda', 'college', 'public', 'Jhenaidah', 'Horinakunda'),
  ('Harinakundra Pilot High School and College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Harinakundu Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Harinakundu Govt. Girls High School', 'school', 'public', 'Jhenaidah', 'Horinakunda'),
  ('Harinakundu Preonath School and College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Hazi Arshad Ali College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Hazi Arshad Ali Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Hazi Bisharat Ali Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Joradah College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Joradah High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('K.B. Academy Pardahalpur', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Kannyadah Monir Uddin Biswas Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Lalan Academy Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Mandar Tala Zorapukuria Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Mandia Ideal College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Mandia Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Mokimpur Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Munshi Abdul Jabbar Dhakil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Narayan Kandi Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Nittanondo Pur Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Pakhimara Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Par Mathurapur Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Pardakhalpur Girls High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Per Folshi Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Porahati High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Raghunathpur Hossain Ali Alim Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Riskhali Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Riskhali High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Shakharidah Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Shaleha Begum Mohila Degree College', 'college', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Shishukali Model High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Sonaton Pur Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Sreefaltola Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Sreepur High School', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Tailtupi High Schol', 'school', 'private', 'Jhenaidah', 'Horinakunda'),
  ('Tola Secondary School', 'school', 'private', 'Jhenaidah', 'Horinakunda');

-- ── JHENAIDAH SADAR Upazila (139) ───────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('A and J College Ram Nagar', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('A Rouf Degree College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Abdur Rakib Girls High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Al Hera Islami Institute, Jhenaidah', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Alhaz Moshiur Rahman College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Amena Khatun College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Anirban Pre-Cadet and High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Anwar Zahid Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Armukhi Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Armukhi Joarder Jalal Uddin High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Asannagar Mohila Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bairatala Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bamonain Palli Mongal High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Baniabahu Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bankira High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Barek Ali Secondary School, Surat', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bari Bathan Adarsha Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bazar Gopalpur School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Berashula Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Berbari High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bhutiar Gati Rosulpur Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bidwasagar Teachers Training College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Bishoy Khali S. M High School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Boidanga Junior High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Chandipur Bishnupada School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Chandipur Painjat Ali Dhakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Chanduali High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Chorkol High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Defalbari Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Deshari Institute of Science and Engineering', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Dhananjoypur Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Dhopabila Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Dohakula Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Durgapur High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Fazar Ali Girls School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Furshondi Govt. Primary School', 'school', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Ghorashal Hamidiya Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Govt Nurunnahar Mohila College', 'college', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Govt. K.C. College', 'college', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Halidhani Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Halidhani High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Harishankarpur J.C. Secondary Biddyapith', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Hat Gopalpur Bhomra Danga Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Hatgopal Pur Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Hiradanga High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Holidhani Girls High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Huda Putia Girl''s High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Islampur (Horipur) K F A High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jamila Khatun Girls High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jattrapur Junior High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jehnaidah Govt. High School, Jhenaidah', 'school', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaida Govt. Secondary Girls High School', 'school', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah Adarsha Teachers Training College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah Collectorate School and College', 'college', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah Pouro Model College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah S. P Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah Technical School and College', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenaidah Technical Training Center', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenidah Cadet College', 'college', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenidah Mohila Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenidah New Academy', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenidah Polytechnic Institute, Jhenaidah', 'polytechnic', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenidah Wazir Ali School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhenidha Magura Sammilito College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jhinaiadah Siddikia Kamil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Jobeda Sorwar Computer and COM College', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('K B High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('K. B. Sammiloni Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('K. K.P. B. High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('K. P. H . High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('K. P. K. B. High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('K.M.H High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Kaluhati Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Kaluhati Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Kanchannagar Model School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Kanuharpur Hazi Ali Akkash Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Khari Khali Mayamoy Girl''s Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Kuthi Durgapur Siddika Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Laudia Pir Dewan Alim Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Laudia Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('M K Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('M. A. Khaleque Mahabiddalaya', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Madhuhati High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Mallik Shahidul Islam Technical College', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Maulanabad Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Mia Kundu Girls High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Modhupur High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Moslem Uddin High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Msharraf Hossain College Jhenidah', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Mudhupur Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Muktijoddah Moshiur Rahman College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Muktijoddha Moshiur Rahman Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Muktijoddha Moshiur Rahman Girls School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Munuria High School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Naboganga Medical Institute of Health Technology', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Nagar Bathan High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Naldanga Ibrahim High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Naldanga Shamsul Alam Khan Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Narayanpur Pancharally Junior High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Narikel Baria Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Narikel Baria Z A High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Nazir Uddin Islamia College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Nur Nagar Siddiqia Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Panami Girl''s High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Panchagram Muktijoddah Moshiur Rahman Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Pashchim Durgapur Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Police Lines Model School', 'school', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Pouro Model School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Primary Teachers Training Institute, Jhenaidah', 'college', 'public', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Principal Moshrraf Hossain Shaleha Khatun Junior School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Progati Pre Cadet School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Putia High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Raghunatahpur High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Raicharan Tarinicharan Degree College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Rajib Ali Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Raku Adarsha Dhakil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Ramchandrapur School and College', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Rangarpota Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('S.M. Matlabur Rahman High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Sabed Ali High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Sadhuati Girls High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Saganna Siddikia Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Science and Technical Institute', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Shaheed Ziaur Rahman Law College, Jhenaidah', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Shahid Smrity Biddyapith', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Shailazanath Junior Girls High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Shekarpur Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Shishu Kunja School and College, Jhenaidah', 'college', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Tikary Bazar Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Udaipur Motiar Rahman Memo High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Uttar Custasugra Siddikia Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Uttar Narayan Pur Secondary School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Utter Narayonpur Dakhil Madrsha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Ziala High School', 'school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Srizony Polytechnic Institute', 'polytechnic', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Riadul Jannat Adarsha Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Agriculture Training Institute Jhenaidah', 'technical_school', 'private', 'Jhenaidah', 'Jhenaidah Sadar'),
  ('Novel Polytechnic and Textitle Institute', 'polytechnic', 'private', 'Jhenaidah', 'Jhenaidah Sadar');

-- ── KALIGANJ Upazila (89) ────────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Abdul Zabbar School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Abu Bakar Biswas Moksed Ali College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Abu Bakar Biswas Moksed Ali Mohila Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Adarsha Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Akter Pur High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Alhaz Amzad Ali and Faizur Rahman Mohila College, Kaligonj', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Asaduzzaman Hosnin Keyabagan Adarsha College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Ayesha Fuljan Memorial Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Aysha Khatun Girls High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Banuria-Chandropara-Sanbandha Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Buzruk Mundia, Hazipur Mundia, Agmundia, Buzidanga Mundia Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('B.I.G.B. Sommilito High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('B.S.B. United Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Borosimla Choto Simla Tilla Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bagergachi Nowdapara Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Baliadanga Mangoljan Sheikh Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Baliadanga Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bangabundhu Sheikh Mujip Viddy Nikaton', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bara Bazar College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Baro Bazar Girls High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Baro Pakhia Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Basudebpur High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Belat Daulatpur Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bethuli Technical and B.M College', 'technical_school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bethuly High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bezpara Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Bhatghara Dayapur Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Boro Talian Dahkil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Chanchra High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Chandpara Dahkil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Chaprail High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Dadpur Dahkil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Damodorpur Karamatia Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Dulal Mundia Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('G G M N Technical and Business Management', 'technical_school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Gaurinathpur Kastobhanga Combined Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Gazir Hat High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Gopal Pur High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Hasanhati Baro Dhopadi Ebadat Ali Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Hat Barobazar High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Iswarba Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Jatir Janak Bangabandhu Sheikh Mujib Memorial Govt. College', 'college', 'public', 'Jhenaidah', 'Kaliganj'),
  ('K.D.H.B.U Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kadirkol Adarsha Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kaligonj Bhuson Girls Junior High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kalukhali Modhupur Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kastovanga Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kastovanga Technical and Business Management College', 'technical_school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Khamer Mundia Gazem Ali Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kola Bazar United High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Kumar Hati Mohammadia Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Lautola College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('M M High School and College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('M.N Sammilita Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mazdia Subarnasara Jagonnathpur Luchia High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mahtab Uddin Govt. Degree College', 'college', 'public', 'Jhenaidah', 'Kaliganj'),
  ('Mandarbaria Chandpara High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mangalpayta Parkhidda College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mobarak Ali High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mobarakganj Sugar Mills Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mokhles Anowar College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Monohar Pur Pukhuria Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Monoharpur Pukuria High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Mostabapur Sommilta High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Naldanga Bhushan Pilot Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Nalvanga Girls High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Nardahi Abbasia Dakil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Natun Bazar United Junior High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Paksharif Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Panch Kahunia High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Pantadanga Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Patbila Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Raigram Banikanta Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Rustom Ali Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sundarpur Chandba Akterpur Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sait Baria Hakkul Huda Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sammilita Dighar Para Junior High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sammiloni Bohumukhi Dakhil Madrasa, Anupompur', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Shahid Nur Ali College', 'college', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Shahpur Choto Ghighati Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Shamsernagar High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Showaib Nagar Kamil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Solimunnessa Pilot Girls High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sommiloni High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sundar Pur Secondary School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Sundarpur Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Tattipur Girls High School', 'school', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Ulla Sammilita Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kaliganj'),
  ('Life Science Veterinary Training Institute', 'technical_school', 'private', 'Jhenaidah', 'Kaliganj');

-- ── KOTCHANDPUR Upazila (42) ─────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Al Amin High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Asannogor Kullagacha High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('B .R High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('B.C..B. High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Balabaria Bagdanga High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Balabaria Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Bohrmpur High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Dayarampur Islamia Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Dhopabila Secondary School, Kotchandpur', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Elangi Mofez Uddin Secondary School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Fulbari Secondary School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('G B J Afsaruddin Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('G. T. College Talsar', 'college', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Hazi Altaf Hossain Horindia Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Jalal Pur High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Jalalpur Dakhil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kagmari Dakil Madrasha', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kagmari High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Khondokar Mosharraf Hossain Govt College', 'college', 'public', 'Jhenaidah', 'Kotchandpur'),
  ('Kotchandpur Alia (Kamil) Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kotchandpur Paura Mohila Degree College', 'college', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kotchandpur Powro College', 'college', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kotchanpur Bahazzel Hossain Mohila Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kotchanpur Girls High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Kotchanpur Govt. Secondary School', 'school', 'public', 'Jhenaidah', 'Kotchandpur'),
  ('Kushna Secondary School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('M. S. L. High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Mohammad Ali Model College', 'college', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Murutia Balarampur Secondary School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('N. B. J. High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('N.K.R. Poura Model High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Panchlia M.L High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Progati Model College', 'college', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Safdarpur Baliadanga Laxmikundu Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('S. D. Degree College', 'college', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Safdarpur Darul Ulum Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Safdarpur Munsur Ali Academy', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Sheikh Mozaffar Hossan High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Sherkali High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('T.I.C. High School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Talsar Kazi Lutfor Rahman Secondary School', 'school', 'private', 'Jhenaidah', 'Kotchandpur'),
  ('Sobdul Sardar Municipal Junior Secondary School', 'school', 'private', 'Jhenaidah', 'Kotchandpur');

-- ── MAHESHPUR Upazila (83) ───────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Al Haz Mofiz Uddin Academy Ruly', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Alampur High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Alfatunnesa College', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Altaf Hossen Khan Junior Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Anando Bazar Dhakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('B.K. Junior Girl''s School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('B.R.A.K.S High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bainchitala Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bainchitala Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bakashpota High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bamongachhi Da.Ne Nu. Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bhairaba Alhera Senior Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bhasanpota Aminnagar Dhakil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Bidya Dhor Pur High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('D.P.G Girls Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Dattanagar S.M.Farm High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Dr. Shaiful Islam College, Katgara', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Fatepur Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Fatepur Gazironnesa Junior Girls School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('G.H.G.P Poura High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Garabaria J.R High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Ghugry Pantapara Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Gopalpur Kola Collegiate School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Gourinathpur Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Govt. Birshrstha Shahid Hamidur Rahman Degree College', 'college', 'public', 'Jhenaidah', 'Maheshpur'),
  ('Gurudah High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Habashpur Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Idrakpur National Ideal High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Jadobpur College', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Jalilpur Alim Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Jalilpur High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Jaluly Madinatul Ulum Dakhil Mdrasha', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Jaluly Model High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Jinnah Nagar Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('K. B. S Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Khalishpur Dhakil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Khalishpur M.L Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Khrow Mondertala Talpotti Para Junior High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Krishno Pur Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Kullah Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Kushadanga Govt. Primary School', 'school', 'public', 'Jhenaidah', 'Maheshpur'),
  ('M. P. B High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Maheshpur Govt. Degree College', 'college', 'public', 'Jhenaidah', 'Maheshpur'),
  ('Maheshpur Govt. Pilot Model High School', 'school', 'public', 'Jhenaidah', 'Maheshpur'),
  ('Maheshpur Paura Laboratory Junior School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Maheshpur Pilot Girl''s High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Maladharpur Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Mandarbaria High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Manderbaria Dakil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Md. Shahidul Islam Degree College', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Modanpur Alhaz Asmot Ullah Biswas Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Moheshpur Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Moheshpur Poura Mohila Degree College', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Mohiuddin Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('N.I. Raghunathpur Borhan Uddin Ahmed Dhahil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Natima Fazil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Natima Kuripol Adarsha High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Nepa Anto Union Darussalam Alim Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Pathra United Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Polianpur Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Porapara High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Porapara H R H S Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Progati Bidya Niketon High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Purandarpur Model Academy', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Rahatullah Sarder Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('S P K Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Samanta Siddikea Dskhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Samonta High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Sasta High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Satpara Model Academy', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Sazia Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Shahaz Uddin High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Shahid Ziaur Rahman College Fatehpur', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Shamsuddin Sardar High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Shamsul Hoda Khan Junior School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Shamsul Huda Khan College', 'college', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Shankarhuda Bathangachi High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Sheikh Hasina Padma Pukur Govt. Degree College', 'college', 'public', 'Jhenaidah', 'Maheshpur'),
  ('Shym Kur Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Sondarpur Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Swaruppur Kushumpur High School', 'school', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Talshar Dhakil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Maheshpur'),
  ('Talshar Secondary School', 'school', 'private', 'Jhenaidah', 'Maheshpur');

-- ── SHAILKUPA Upazila (91) ───────────────────────────────────────────────────
insert into public.education_institutions (name, type, ownership_type, city, area)
values
  ('Putimari Aoulia Dakhil Mad Rasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('77No. Kabirpur Model Govt. Primary School', 'school', 'public', 'Jhenaidah', 'Shailkupa'),
  ('A R B Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Abaipur Jamuna Shikder College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Abaipur Ramsundar Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Abdul Jabbar Junior School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Abu Ahmed Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Adil Uddin College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Alamdanga Junior Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Anhintapur High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Aoudha Sammilita High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Ashan Nagar A.B.C.D Alim Madrash', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Aushia Ideal Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('B L K Technical and Business Management College', 'technical_school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('B.A.M.S Junior Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('B.K.L.K Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('B.L.K Mir Ismail Hossain High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bagni Sapta Polli Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bagutia Gopalpur High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bakey Shiddi High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bangabandhu Memorial College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bardah Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Basanta Pur Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Basantapur High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Benipur Multilateral High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bhatai High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Biprabgodia Secondary High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Bir Muktijoddha Abdul Hai College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Boria Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Dautia Sammilita Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Dhawrah Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Dhawrah Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Digholgram Piragati Dakhil Madrasah', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Dignagar Union High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Dudhshar Digital School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Dudshar Abdus Sobhan Joarder Junior School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Falia Shahadev Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Fulhari Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Fulhari High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Gabindopur High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Garagonj High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Garagonj Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Haji Md. Shamsuddin Biswas Junior School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Hat Fazilpur High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Hetampur Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Jangalia Kari A. Kader (RH) Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Jarip Biswas Degree College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kabirpur Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kamanna M.L. High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kancher Kole College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kancherkole Islamia Fazil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kancherkole Mariam Nessa Sec. Girl''s High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Katlagari Degree College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Katlagari Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Katlagari Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kazi Para High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Khalfalia Millon ML High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Kismat Ali Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Lion Monoara Islam Junior Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Madla High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Miah Jinnah Alam Degree College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Mingram Keramot Ali Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Mirzapur Amena Khtun High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Monoharpur Kabi Golam Mostafa Secondary School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Montazer Rahman Mia Girls High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Mouban High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Muktijoddha Abdus Sattar Shikder College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Nabaday Girls High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Nadpara Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Nadpara Jubo Mlion High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Nagerhat High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Nagirat Makrampur D Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Panch Pakhia Siddiquea Fazil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('PDR High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Rabaya Khatun Model Secondary Girls School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Royera Islamia Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shailkupa Govt. Pilot High School', 'school', 'public', 'Jhenaidah', 'Shailkupa'),
  ('Sarutia High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shailkupa City College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shailkupa Fazil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shailkupa Govt Degree College', 'college', 'public', 'Jhenaidah', 'Shailkupa'),
  ('Shailkupa Mohila Degree College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shailkupa Pilot Girls High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Sheikh Para Dukhi Mahamud Degree College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Sheikhpara Rahatonnessa Girl''s School and College', 'college', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shekhar High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shiddi Dakhil Madarasah', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Shohid Nagar Dakhil Madrasa', 'madrasa', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Tribeni High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Umedpur Girls High School', 'school', 'private', 'Jhenaidah', 'Shailkupa'),
  ('Umedpur High School', 'school', 'private', 'Jhenaidah', 'Shailkupa');
