-- Storage buckets and policies (spec §15).
-- Public buckets: avatars, organization-logos, opportunity-images, community-media
-- Private buckets (signed URLs only): certificates, resumes
--
-- Path convention for user uploads: `<bucket>/<auth.uid()>/<random-filename>`
-- Randomized filenames are generated client-side (uuid) per spec §15.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 2097152,
    array['image/jpeg', 'image/png', 'image/webp']),
  ('organization-logos', 'organization-logos', true, 2097152,
    array['image/jpeg', 'image/png', 'image/svg+xml', 'image/webp']),
  ('opportunity-images', 'opportunity-images', true, 5242880,
    array['image/jpeg', 'image/png', 'image/webp']),
  ('community-media', 'community-media', true, 5242880,
    array['image/jpeg', 'image/png', 'image/webp']),
  ('certificates', 'certificates', false, 10485760,
    array['application/pdf', 'image/jpeg', 'image/png']),
  ('resumes', 'resumes', false, 10485760, array['application/pdf'])
on conflict (id) do nothing;

-- Owners manage files under their own prefix. Public buckets serve reads
-- without policies; private bucket reads are restricted to the owner
-- (signed URLs are generated by trusted server contexts).
do $$
declare bucket text;
begin
  foreach bucket in array array['avatars', 'organization-logos',
                                'opportunity-images', 'community-media',
                                'certificates', 'resumes']
  loop
    execute format('create policy %I on storage.objects for insert to authenticated
                    with check (bucket_id = %L
                                and (storage.foldername(name))[1] = auth.uid()::text)',
                   'storage_' || bucket || '_insert_own_prefix', bucket);

    execute format('create policy %I on storage.objects for update to authenticated
                    using (bucket_id = %L
                           and (storage.foldername(name))[1] = auth.uid()::text)
                    with check (bucket_id = %L
                                and (storage.foldername(name))[1] = auth.uid()::text)',
                   'storage_' || bucket || '_update_own_prefix', bucket, bucket);

    execute format('create policy %I on storage.objects for delete to authenticated
                    using (bucket_id = %L
                           and (storage.foldername(name))[1] = auth.uid()::text)',
                   'storage_' || bucket || '_delete_own_prefix', bucket);
  end loop;
end $$;

create policy storage_certificates_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'certificates'
         and (storage.foldername(name))[1] = auth.uid()::text);

create policy storage_resumes_select_own on storage.objects
  for select to authenticated
  using (bucket_id = 'resumes'
         and (storage.foldername(name))[1] = auth.uid()::text);
